### ISSUE TITLE
[doc] 9.2  Enabling Eirini

### ISSUE THREAD

**Issue by it-slav** [SUSE/doc-cap#1001]
9.2  Enabling Eirini:

https://documentation.suse.com/suse-cap/2.1/single-html/cap-guides/#sec-cap-eirini-enable

What is? 
--cluster-domain set to cluster.local
How do I verify that?

**Comment by claudioser** [comment]
Peter,
you can set in the values file clusterDomain: cluster.local, only if your cluster has been setup with diff internal dns.
you can check, by kubectl -n kube-system get configmap kubeadm-config -o yaml |grep dnsDomain
I had this issue once with setting up with minibroker with 1.5.2
 Hope this helps.

**Comment by btat** [comment]
Replaced by https://github.com/SUSE/doc-cap/issues/1007
