### ISSUE TITLE
Separation of marketing-esque material from core documentation

### ISSUE THREAD

**Issue by btat** [SUSE/doc-cap#1011]
From feedback, it was suggested some material falls more towards the marketing category and could be removed from the core documentation. An example is the diagram comparing the different "X as a Service" models.

To be discussed.

**Comment by gaktive** [comment]
Main point: https://documentation.suse.com/suse-cap/2.1/single-html/cap-guides/#sec-cap-architecture as 1.3 pops up way too early and doesn't relate to the core product usage. Maybe an appendix if still needed?

**Comment by btat** [comment]
Closing this for now due to resource limitations. Will revisit/reopen in the future when resources permit.
