### ISSUE TITLE
Emphasis on Helm 3 requirement

### ISSUE THREAD

**Issue by btat** [SUSE/doc-cap#1016]
Helm 3 is currently mentioned as a requirement, but it is embedded in the flow of the intro paragraph in the Helm Installation section. Based on feedback, this is easily missed and needs to made more prominent

**Comment by KucharczykL** [comment]
Would it be OK to change the &helm; entity to "Helm v3"? It would alleviate the need for a prominent warning in one or two places and it would also make sure there can be no mistake which version of Helm it's being talked about.

**Comment by btat** [comment]
If I'm not mistaken we use the `&helm`; entity a considerable amount when referring to other things like Helm charts, Helm values, or just Helm in general and not just for the Helm client. It's probably better to keep the scope of the fix to the Helm install section to avoid a large amount of review for contextual correctness if we change the current entity.
