### ISSUE TITLE
Expansion of User Guide

### ISSUE THREAD

**Issue by btat** [SUSE/doc-cap#1018]
The current user guide only lists the usage of certain cf cli commands. 

We should add:
- end to end example use cases of using these commands
- more real world/advanced use cases
    - building custom buildpacks https://www.suse.com/media/guide/how_to_build_your_own_custom_buildpacks_guide.pdf
    - blue/green and canary deployments

**Comment by gaktive** [comment]
Also to be considered:
- autoscaler
- vcap services: how they work
- Credhub
- org & spaces permissions: how the sharing model works
- quotas
- debugging staging errors
- testing database connectivity

**Comment by btat** [comment]
Closing this for now due to resource limitations. Will revisit/reopen in the future when resources permit.
