### ISSUE TITLE
[doc] 4.5  Deployment Configuration

### ISSUE THREAD

**Issue by asettle** [SUSE/doc-cap#1021]
4.5  Deployment Configuration:

https://susedoc.github.io/doc-cap/master/single-html/cap-guides/#sec-cap-caasp-config

Again, probably pedantic: `The format of the kubecf-config-values.yaml file has been restructured completely in Cloud Application Platform 2.x. Do not re-use the Cloud Application Platform 1.x version of the file. Instead, see the default file in the appendix in Section A.1, “Complete suse/kubecf values.yaml File” and pick parameters according to your needs.`

I think this should be called out in an `<important>` tag. It's pretty much key to the following steps, and it gets a bit swallowed by the information.

**Comment by KucharczykL** [comment]
There are two warnings with only a line in-between but I think that's fine.
