### ISSUE TITLE
[doc] 4.12  Add the Kubernetes Charts Repository

### ISSUE THREAD

**Issue by asettle** [SUSE/doc-cap#1022]
4.12  Add the Kubernetes Charts Repository:

https://susedoc.github.io/doc-cap/master/single-html/cap-guides/#sec-cap-addrepo-caasp

Does the command prompt not need to be `helm3` rather than `helm`? (We had the same problem with the SES docs, hence the half question, half bug)

**Comment by btat** [comment]
I think it's because in an earlier part we do `sudo update-alternatives --set helm /usr/bin/helm3`

**Comment by asettle** [comment]
Ohhhhhh I must have missed that! Thanks Billy :) will happily close.
