### ISSUE TITLE
[doc] 8.1  Deploy Stratos on SUSE® CaaS Platform

### ISSUE THREAD

**Issue by asettle** [SUSE/doc-cap#1025]
8.1  Deploy Stratos on SUSE® CaaS Platform:

https://susedoc.github.io/doc-cap/master/single-html/cap-guides/#sec-cap-stratos-prod

`Wade through the nag screens about the self-signed certificates and log in as admin with the password you created in stratos-config-values.yaml`

"nag" is a colloquial term for "annoying/harassing someone", I'm not convinced this is appropriate terminology for a technical guide unless this is an official terminology? Opening a bug just in case :)

**Comment by btat** [comment]
Gah, I thought we fixed this :|

Action item: convert to more appropriate phrasing
