### ISSUE TITLE
Link to terraform templates for 2.1 deployment

### ISSUE THREAD

**Issue by satadruroy** [SUSE/doc-cap#1034]
We should provide an option for a "one-click" deployment using the terraform templates. Something like "optionally, you can deploy CAP 2, Stratos and Metrics on AWS, Azure or GCP using Terraform by following the instructions from ..."

https://github.com/SUSE/cap-terraform

We don't need to provide any detailed instructions as users should be able to follow the instructions from the repo.

@troytop - hope this is ok.

**Comment by troytop** [comment]
We should point to the CAP Installer images in the public cloud (if we can get good links to those) as well as the cap-terraform instructions. If we can't work in the public cloud CAP Installer, then yes, just a link to cap-terraform would be better than nothing.

**Comment by satadruroy** [comment]
The 2.1 installers on the public cloud marketplaces are not up yet. Until then a link to the cap-terraform should be ok?
