### ISSUE TITLE
Upgrading a non-High Availability Deployment to High Availability

### ISSUE THREAD

**Issue by lcavajani** [SUSE/doc-cap#104]
2.14.1  Upgrading a non-High Availability Deployment to High Availability

http://docserv.nue.suse.com/documents/CAP_1/cap-deployment/single-html/#sec.cap.ha-prod-upgrade

Some backslashes are missing in:

helm upgrade suse/cf \
--name susecf-scf
--namespace scf \
--values scf-config-values.yaml \
--values scf-sizing.yaml
--set "secrets.UAA_CA_CERT=${CA_CERT}"

should be

helm upgrade suse/cf \
--name susecf-scf \
--namespace scf \
--values scf-config-values.yaml \
--values scf-sizing.yaml \
--set "secrets.UAA_CA_CERT=${CA_CERT}"

**Comment by lcavajani** [comment]
The same applies for http://docserv.nue.suse.com/documents/CAP_1/cap-deployment/single-html/#sec.cap.ha-prod

**Comment by cjschroder** [comment]
thanks @lcavajani.

**Comment by cjschroder** [comment]
https://github.com/SUSE/doc-cap/commit/8fa00110d569fb2427e433797498be2da6fdd232
