### ISSUE TITLE
Upgrading a non-High Availability Deployment to High Availability

### ISSUE THREAD

**Issue by lcavajani** [SUSE/doc-cap#105]
2.14 Example High Availability Configuration
2.14.1  Upgrading a non-High Availability Deployment to High Availability

http://docserv.nue.suse.com/documents/CAP_1/cap-deployment/single-html/#sec.cap.ha-prod
http://docserv.nue.suse.com/documents/CAP_1/cap-deployment/single-html/#sec.cap.ha-prod-upgrade

If UAA is deployed in HA (2 in this examples), getting the SECRET returns duplicated values, hence, getting the CA_CERT will return an empty value:

$ SECRET=$(kubectl get pods --namespace uaa \
  -o jsonpath='{.items[*].spec.containers[?(.name=="uaa")].env[?(.name=="INTERNAL_CA_CERT")].valueFrom.secretKeyRef.name}')

$ echo $SECRET
secrets-2.10.1-1 secrets-2.10.1-1

$ CA_CERT="$(kubectl get secret $SECRET --namespace uaa \
  -o jsonpath="{.data['internal-ca-cert']}" | base64 --decode -)"    

$ echo $CA_CERT

This can be fixed by adding a simple awk to get the first value:

$ SECRET=$(kubectl get pods --namespace uaa \
 -o jsonpath='{.items[*].spec.containers[?(.name=="uaa")].env[?(.name=="INTERNAL_CA_CERT")].valueFrom.secretKeyRef.name}' | awk {'print $1'})

**Comment by cjschroder** [comment]
Hmm, when I tested this it all looked OK. I also used echo to verify-- I'll take another look.

**Comment by lcavajani** [comment]
It works fine with just one uaa pod, what configuration did you have when you tested ?
