### ISSUE TITLE
[doc] 19.2  Enabling and Disabling the App-AutoScaler Service

### ISSUE THREAD

**Issue by deepaksharma009** [SUSE/doc-cap#1058]
19.2  Enabling and Disabling the App-AutoScaler Service:

https://documentation.suse.com/suse-cap/2.0/html/cap-guides/cha-cap-app-autoscaler.html#sec-cap-enable-app-autoscaler

In Sentence, "To enable it, add **the following the following** block to your kubecf-config-values.yaml file." , there is repeating words "**the following**".

**Comment by btat** [comment]
Thanks. Fixed in https://github.com/SUSE/doc-cap/commit/75a6184620248771375575908244235db4d0ec5e and will be published later
