### ISSUE TITLE
The template for postgres usb deployement has wrong indentation

### ISSUE THREAD

**Issue by fsundermeyer** [SUSE/doc-cap#106]
@greygoo reported in [bsc 1100388](https://bugzilla.suse.com/show_bug.cgi?id=1100388):

When trying to deploy postgres following the instructions at http://docserv.nue.suse.com/documents/CAP_1/cap-deployment/single-html/#sec.cap.configure-postgresql I realized that the template for usb-config-values.yaml does contain a wrong indentation. 

This is the snippet from the docs, I marked the lines which are not correctly indented with an "X":

----------------------------------snip--------------------------------------

    env:
      # Database access credentials
       SERVICE_POSTGRESQL_HOST: postgres.example.com
       SERVICE_POSTGRESQL_PORT: 5432
       SERVICE_POSTGRESQL_USER: pgsql-admin-user
       SERVICE_POSTGRESQL_PASS: pgsql-admin-password
      # The SSL connection mode when connecting to the database.  For a list of
      # valid values, please see https://godoc.org/github.com/lib/pq
    X SERVICE_POSTGRESQL_SSLMODE: disable
      
      # CAP access credentials, from your original deployment configuration 
      # (see Section 2.4, “Configuring the SUSE Cloud Application Platform Production Deployment”)
      CF_ADMIN_USER: admin
      CF_ADMIN_PASSWORD: password
      CF_DOMAIN: example.com
      
      # Copy the certificates you extracted above, as shown in these
      # abbreviated examples, prefaced with the pipe character
      
      # SCF cert
      CF_CA_CERT: |
       -----BEGIN CERTIFICATE-----
       MIIE8jCCAtqgAwIBAgIUT/Yu/Sv4UHl5zHZYZKCy5RKJqmYwDQYJKoZIhvcNAQEN
       [...]
       xC8x/+zT0QkvcRJBio5gg670+25KJQ==
       -----END CERTIFICATE-----
       
       # UAA cert
    X  UAA_CA_CERT: |
        -----BEGIN CERTIFICATE-----
        MIIE8jCCAtqgAwIBAgIUSI02lj0a0InLb/zMrjNgW5d8EygwDQYJKoZIhvcNAQEN
        [...]
        to2GI8rPMb9W9fd2WwUXGEHTc+PqTg==
        -----END CERTIFICATE-----
       SERVICE_TYPE: postgres   
        
    Xkube:
    X organization: cap
    X registry: 
    X   hostname: "registry.suse.com"
    X   username: ""
    X   password: ""
    
----------------------------------snip--------------------------------------

This would be a correctly indented config:

----------------------------------snip--------------------------------------

    env:
      # Database access credentials
      SERVICE_POSTGRESQL_HOST: 172.24.44.151.xip.io
      SERVICE_POSTGRESQL_PORT: 5432
      SERVICE_POSTGRESQL_USER: pgsql-admin-user
      SERVICE_POSTGRESQL_PASS: postgres
      # The SSL connection mode when connecting to the database.  For a list of
      # valid values, please see https://godoc.org/github.com/lib/pq
      SERVICE_POSTGRESQL_SSLMODE: disable
      
      # CAP access credentials, from your original deployment configuration 
      # (see Section 2.4, “Configuring the SUSE Cloud Application Platform Production Deployment”)
      CF_ADMIN_USER: admin
      CF_ADMIN_PASSWORD: password
      CF_DOMAIN: 10.86.1.13.xip.io
      
      # Copy the certificates you extracted above, as shown in these
      # abbreviated examples, prefaced with the pipe character
      
      # SCF cert
      CF_CA_CERT: |
        -----BEGIN CERTIFICATE-----
        MIIE8jCCAtqgAwIBAgIUK6y/yKkVbYbfvWXXcFCX6zF5iiowDQYJKoZIhvcNAQEN
        BQAwETEPMA0GA1UEAxMGU0NGIENBMB4XDTE4MDcwNjA3MjkwMFoXDTQ4MDYyODA3
        MjkwMFowETEPMA0GA1UEAxMGU0NGIENBMIICIjANBgkqhkiG9w0BAQEFAAOCAg8A
        MIICCgKCAgEAzewG2q7g8bNF5TrmeaP3rLaiGDqi5YanszFK69RhHFivtV9zHnbj
        YwAbCe7BuY8oFkEmgYdwscRgX4IG/BhtaAtv9Bvkmt668IbNsvHlgXkHeTYz6fWR
        d5mJTnyIIOaguYW97WfoO6tecdJvXzhvzPWkzZTV6+fOSjlGtRk9o3WhAclA03l7
        63+KCXqTHmWU5iGzdOFMEXvyzgkAVP4Mby4dVWIN+TAO/RyX0dxaBC2enNYxUadW
        LwrE2rJ323/kT5dzITzdWPHmMBiYHomgQrXtcbfWblmYjGzF59hotfNEuYn/rBUW
        ub1J2QLA3rSIISqafhaqjYMj5WInnBWypY+yZr8qnrmUNruICDkwkpacbbmZGUyE
        UJhp/iI+YSiwVyX7BWN3uvtnbmGyh+NVUqvpB2fS6o4tigiVBfy+2hy6RLoWTFew
        UDhxNGBC4uuPxBg/6T4JrToflG9bXGaz3OP7eko41vqWbg1uNuNi6Zxn5DuAwZb1
        g+Tj8mpUZKNdVBJCF0l+aKU4mJZvSOtOWKliG5r0hstZ2T6eUR+g2VcuL2+XG/++
        /kVR/FNhOyWjzAAXp5nx/B9ZWfatLoh0bPXzxBWAMTbYLr91U/HIO+5vcZgd5xAo
        yj9isUY9c8rRuYdGpLhenwH4yvxT6kDxgoFkYHRIVl8gfaZB/7JmWV0CAwEAAaNC
        MEAwDgYDVR0PAQH/BAQDAgEGMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFKob
        g9okSlD3UhrVIv+QXGLzGfIAMA0GCSqGSIb3DQEBDQUAA4ICAQB2BKWdmq1YCiMK
        F/RDXf/AytC4Xn21nYltxM95LyS0sueoMv2aFj4DD9ujgpzhpLBg/6j0KdWrNxzR
        GJ8ot+4ySRqI4ymJLu2cxj6254uzLvPIT6C2oHXrsZ/jpaOdJAy1tlloDyM73rNC
        GoaJ8xRdzqN4WCin8aDryAxtKMULKDf5CpVFCrjEV3Cp2IpXJXk1KkOsTTBJhY4o
        s3QaVcFkya0wtEXFiDhORDcIeK5t7s0oznhj5ezcMlu7CFmBqbO+q7CTRbldJEhj
        rbQirJrJ9RA4LfF/HVYiw6KQ3On4dd1hMRJnfBVz9TkMWhIqnA6na2265qQfuHPS
        TMRWgHjeIUo8d6kPADwybwE5vAcJGhNTYuBVprXWoGWpDKWQoStEXrXYxYGOjYbv
        f9JTQQoL7C7ZlzHEak6m9QPJI4zd9kJIyh0SZumTatEmo6yVBIrhVgT0q0oCV/1x
        QAiIKPIo/Mc8rW/iwBLU0vRUs2MvM+iqN8xsuHfrMdMfmZ48KlUrG/R+30UakA6I
        wdM45jMDWMvoCKbV1C+f1E9zeptaSAuAM6/SGPYaI8zxZiCb+eErM1t5U5XiAYnW
        bGYpmW1FAyfnJLXPz6LBshle2NvVxRtA/5pFDj6jzAE5yX5RL8ivW0zTLa/os4Ll
        oA2yHX7/uLZ7Dz3hNQnlHg5UE402Fw==
        -----END CERTIFICATE-----
       
      # UAA cert
      UAA_CA_CERT: |
        -----BEGIN CERTIFICATE-----
        MIIE8jCCAtqgAwIBAgIUMvKiDUPnkZzwU3NgfvXJpgmcUDwwDQYJKoZIhvcNAQEN
        BQAwETEPMA0GA1UEAxMGU0NGIENBMB4XDTE4MDcwNjA3MjQwMFoXDTQ4MDYyODA3
        MjQwMFowETEPMA0GA1UEAxMGU0NGIENBMIICIjANBgkqhkiG9w0BAQEFAAOCAg8A
        MIICCgKCAgEAoqJMj3i/CU3useDnrPOKURkcFZRhUiBzM2h73bs7Kof3qK+vTQpr
        e4rTf2MIsXds4+GYxdDCI2HbitiXQZkZS1n3uYurRuBMwn7mJpHTTu6VdBy68wQA
        U5AtvjIYl3N3BSJ8beVc3s/NjGgG1gOnZ0nKjrEl+sxALulQAM6ujisJ5M9dVvzU
        ydyMGsC+KBS8IoR37wByQ34XL+SMdw+WVNzAXn0BpLLxM8Owzz4CAjDTW4c2BSVo
        CCcU+/TG+Lu5CsgrqBGyhPBSiupbhAPQO0N/+kV5xyRA5NTnhqq8rtRuXqrgwY9T
        Mo3Lv4lYPP3YhaMyxZ+BTQR81/FqL/e5Mn2T1EmHj5yHaVmZtUGivjpIu83Ho+Ie
        /VUhjk0ZHoN3Qv2/etu//i37P1obyUrjfPZgkdGShK3N/Vpw+3ELT+CHUJpcPWn1
        DoNLtI4UKjQnh1XfudZKSB4bU+rgqZVmGsAMyrMFwKD/KlPSf9FmLe3JiEjdlzvh
        Yh6vcuJE5X0WqYypVQzq3Rji+erva1Vg8gf9kYmShtAbNVx8NO7Jat9WeqbgyFVz
        dNhHQqG/0d4RhsVChRUCHnhKEPWvRZ/bW4TSQmK8wqxVJBCPC+hZ436BrdEnWI/o
        wuS6h3XJEE6JMHYmcdX88gXP1ij8qs4DqjG0Geh77MrGMfBJnjR49X0CAwEAAaNC
        MEAwDgYDVR0PAQH/BAQDAgEGMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFBAe
        OdcaZWm7KUMUbmfelqXGJ+XGMA0GCSqGSIb3DQEBDQUAA4ICAQAhu5bpQQK2P8in
        Al/hKmW/plOtJEw94aBprPYkSJojPaw2AEGXz1IelW8SBYTaAfZJGRJwQf/L+Rfq
        eV4EXN82zQz3SEqjk2xZ4Rg/YAXPkmPfS8az4Acb/ONtipfp4M3jrcmiKSoekbF2
        MNkfO+Xng9EAEUg0klZFu+tfGcMSGV7q2vWiYF80FQKQyJ6U8QwgA0HB3SBuSQ/H
        lVhQr9E8ohCDx7DurW9vK18OhpJHFoQlivfer/lBp87ofXQgeFu7HSEN3wyjSPB2
        zaCmw0MjeYlX5dtQA6F1e7zy6M3XhnWaq3UtFAb36AutJgIQq4PkCuWUp2NcwlbB
        xk2QNssfV/doxhguURgk8wQP04Wn/jdR1wgyiZKXPcxuLBkWJ2o58cf3paVq7lL+
        Cau/y9ODC3UTUg4NBsQ8bkIE3GaS9wTF0WXy2wlnnXr8TqGNXCq+gPniSq2vzugi
        qZ+9cm3yA2V0AN0wTaKBVtZynrStsl8HTCRcQYCC4EZoco4+lvxVVEimRLp4mOJD
        pYRoBvliBZQTtYhAxeK3fG2cH+jkS7OW9ML4oF0ObiIh2CLnZOXMU4ZRAIh2ZeKe
        k29e7yrAHds4C/RphDtOPV1/QNIEBGXDodxPB++V4bnDsfXEx8MsIzuy4+OXKXKl
        d6ccko7iKHt1WoDKWzsz3Ey1U66SMg==
        -----END CERTIFICATE-----
      SERVICE_TYPE: postgres   
        
      kube:
        organization: cap
        registry: 
          hostname: "registry.suse.com"
          username: ""
          password: ""
    
----------------------------------snip--------------------------------------

**Comment by cjschroder** [comment]
@greygoo Thanks for finding this-- https://github.com/SUSE/doc-cap/pull/109
