### ISSUE TITLE
New for 1.2: EKS support

### ISSUE THREAD

**Issue by gaktive** [SUSE/doc-cap#107]
We will be adding support for a new platform with 1.2: EKS on Amazon AWS.

We have preliminary information on setup here: https://github.com/SUSE/cloudfoundry/wiki/Deployment-on-Amazon-EKS

This has been validated by Dev, so QA needs to confirm that once they test it.

**Comment by cjschroder** [comment]
Blocked because there are not enough resources to create an EKS cluster: "The maximum number of VPCs has been reached....The maximum number of internet gateways has been reached"

**Comment by cjschroder** [comment]
EKS still broken, still blocked.

**Comment by cjschroder** [comment]
this may be resolved as I was finally able to launch a stack. however there is a newer priority, so this goes to second place in line.

**Comment by cjschroder** [comment]
First draft is published https://github.com/SUSE/doc-cap/commit/3add2e2556e9d686658923551c81bbfbc1347ce2
It is far from perfect, but customers are telling us they would rather have imperfect docs than no docs.

Still needs load balancer.
