### ISSUE TITLE
Document DNS requirements, with examples

### ISSUE THREAD

**Issue by cjschroder** [SUSE/doc-cap#113]
Currently, the Deployment Guide handwaves away name services. We must provide authoritative requirements, and stop evading with xip.io and nip.io.

**Comment by cjschroder** [comment]
see stackato docs

**Comment by gaktive** [comment]
Stackato 3.6.2 docs: http://docs.stackato.com/

**Comment by cjschroder** [comment]
something like this would be fab: http://docserv.nue.suse.com/documents/SUSE_OpenStack_Cloud_7/suse-openstack-cloud-deployment/single-html/#sec.depl.req.network.allocation

**Comment by troytop** [comment]
Closing as a duplicate of newly modified/generalized #78
