### ISSUE TITLE
cf backup tool: refinement to how restore actually works.

### ISSUE THREAD

**Issue by gaktive** [SUSE/doc-cap#114]
There have been assumptions as to how the backup/restore plugin does restores, so we have some updates in a couple PRs:
https://github.com/SUSE/cf-plugin-backup/pull/60
https://github.com/SUSE/cf-plugin-backup/commit/aecdcb8b14c9f7387e729b04f50cf15d92581279

Context: https://trello.com/c/e1GeBtZb/712-cf-backup-better-documentation-as-to-how-restore-works

**Comment by cjschroder** [comment]
https://github.com/SUSE/doc-cap/pull/123
