### ISSUE TITLE
Added support for structured properties such as requiring client certs in the gorouter

### ISSUE THREAD

**Issue by gaktive** [SUSE/doc-cap#116]
We have added a new property ROUTER_TLS_PEM to allow client certificates to be added in the gorouter: https://github.com/SUSE/scf/pull/1613
Context: https://trello.com/c/ttQFiiL2/723-we-need-to-be-able-to-require-client-certs-in-the-gorouter

Key point:
> ClientSSL: Please describe how the gorouter enforces two-way-ssl (i.e. how to "require" ClientSSL certifikates). Please describe how to configure the TrustStore of those certificates.

> ServerSSL: Please describe how to chain multiple certificates together to terminate SSL for multiple domains.

> Expressed as stories, these would be:

> As a CAP operator
> I want to enable validation of client certificates in TLS handshakes with clients as described in https://docs.cloudfoundry.org/adminguide/securingtraffic.html#gorouter_mutual_auth
so that end users can run applications that are only accessible to clients with specific valid certs

> As a CAP operator
> I want to be specify multiple signed/issued SSL certificates for the various domains hosted on my particular CAP cluster so that end users HTTPS connections terminate SSL at the CF router for multiple domains

This is part of a new internal functionality tied to structured properties now enabled within SCF. This isn't customer facing at all but we may be adding more functionality into this sphere depending on customer requests.

**Comment by btat** [comment]
Example for ROUTER_TLS_PEM provided as part of PR #153
