### ISSUE TITLE
Document connecting to the Azure service broker.

### ISSUE THREAD

**Issue by gaktive** [SUSE/doc-cap#117]
We've tried out CAP with the built-in Azure service broker. The steps on its usage noted here, though we have to properly summarize the information as most of this written during discovery: https://trello.com/c/sCzODvSj/716-3-test-and-document-azure-service-broker

It is important to note that support for the Azure service broker itself is handled by Microsoft, not SUSE.

**Comment by cjschroder** [comment]
https://trello.com/c/1XFoSGNW/292-azure-service-broker

**Comment by cjschroder** [comment]
Waiting for information...this whole process looks over-complicated.

**Comment by cjschroder** [comment]
closing for PR #260
