### ISSUE TITLE
2.11 upgrade needs additional helm command line option

### ISSUE THREAD

**Issue by alexjh** [SUSE/doc-cap#119]
https://github.com/SUSE/cf-ci/pull/147 shows how we do this in the QA upgrade pipeline.

Upgrading from 2.10 needs a `--recreate-pods` option given to the helm upgrade cf command. This should only be needed for 2.11. Upgrading from 2.11 to a future version shouldn't need this because all of the pods should always be in a ready state.

**Comment by cjschroder** [comment]
Thanks!
https://github.com/SUSE/doc-cap/pull/122
