### ISSUE TITLE
App Autoscaler

### ISSUE THREAD

**Issue by gaktive** [SUSE/doc-cap#120]
We'll be adding the App Autoscaler into 1.2, though it'll be considered experimental at this stage. This ties into an upstream project and will be off by default.

QA still need to test this but we can start documenting what we have whilst then pointing upstream.

Trello: https://trello.com/c/3wEpZBN4/641-8-implement-app-autoscaler-non-ha
Upstream: https://github.com/SUSE/scf/pull/1594

**Comment by troytop** [comment]
Since App Autoscaler will be marked Experimental in 1.2.1, it's more realistic to put this on the 1.3 milestone.

**Comment by troytop** [comment]
Refer to API and CLI instructions here: https://github.com/cloudfoundry-incubator/app-autoscaler/blob/develop/docs/Readme.md#use-app-autoscaler-service

**Comment by troytop** [comment]
Note that there's an upstream UI for app-autoscaler here: https://github.com/cloudfoundry-incubator/app-autoscaler-ui

Work is underway to integrate this with Stratos(!) but in the meantime, people will need to know how to deploy this to CAP as a CF app, so they'll need to be able to retrieve the kube secrets to set things up.

Some of those same secrets may be needed for CLI access too.

**Comment by troytop** [comment]
Autoscaler is currently off by default. to enable it, add the following to the scf helm values:

```
scaling:
  autoscaler_actors:
    count: 1
  autoscaler_api:
    count: 1
  autoscaler_metrics:
    count: 1
  autoscaler_postgres:
    count: 1
```

See `helm inspect suse/cf` for the full, commented list of available values.
