### ISSUE TITLE
Prequisites for sidecars

### ISSUE THREAD

**Issue by andreas-kupries** [SUSE/doc-cap#124]
http://docserv.nue.suse.com/documents/CAP_1/cap-deployment/single-html

The doc refers at one point to `helm search suse`.

It never mentions `helm repo add suse https://kubernetes-charts.suse.com` as prequisite.

**Comment by cjschroder** [comment]
'helm repo add' is referenced at the beginning of the deployment process in chapter 2, and all operations after that are upgrades and additions. Presumably customers will not be trying to add sidecars to a non-existent CAP deployment.  I added a few cross-references in any case
https://github.com/SUSE/doc-cap/pull/129
