### ISSUE TITLE
Expand PSP information to cover sidecars

### ISSUE THREAD

**Issue by gaktive** [SUSE/doc-cap#125]
Some excitement today whereby we discovered that sidecars weren't working with CaaSP v3. 

PodSecurityPolicy was the issue whereby we had to create rules so that the documented `postgres-sidecar` and `mysql-sidecar` namespaces were similar to what we have for `scf`, `uaa` and `stratos-ui`. Our main CaaSP section should be applied to the MySQL and Postgres sidecar sections to indicate that whatever namespace is used, it will need a PSP. Without the PSP, the sidecar will fail on any version of CAP installed on CaaSP v3 (or v2 if PSP is optionally used). 

Bug discovered: https://trello.com/c/nnpMhl8S/754-usb-postgres-sidecar-fails-when-deploying-with-context-deadline-exceeded
Section of docs with current PSP info: https://www.suse.com/documentation/cloud-application-platform-1/singlehtml/book_cap_deployment/book_cap_deployment.html#sec.cap.caasp-3
Section of docs that need PSP info: https://www.suse.com/documentation/cloud-application-platform-1/singlehtml/book_cap_deployment/book_cap_deployment.html#sec.cap.configure-mysql (and Postgres)

**Comment by cjschroder** [comment]
So, what's the fix? Will simple additions to the config file do the job? e.g.

````
- kind: ServiceAccount
  name: default
  namespace: postgres-sidecar

**Comment by cjschroder** [comment]
http://docserv.nue.suse.com/documents/CAP_1/cap-deployment/single-html/#idm140434459881680

Please review! Not sure if `kubectl create` or `kubectl apply` is the correct command.

**Comment by cjschroder** [comment]
https://github.com/SUSE/doc-cap/pull/126
https://github.com/SUSE/doc-cap/pull/128
