### ISSUE TITLE
Prerequisites

### ISSUE THREAD

**Issue by lcavajani** [SUSE/doc-cap#127]
7.1  Prerequisites

http://docserv.nue.suse.com/documents/CAP_1/cap-deployment/single-html/#sec.cap.prereqs-service-broker

Regarding the command for "Then apply this new PSP configuration before you deploy your new service broker sidecar with this command: "

Considering the objects of cap-psp-rbac.yaml are already created, using 'kubectl create' would issue an error saying it's already created so you have to use 'kubectl apply'.

With apply, kubectl will say the created objects with no modifications are "unchanged" and it will modify "applied" the objects you want to modify.

**Comment by cjschroder** [comment]
Thanks @lcavajani! The upstream docs are voluminous, but not enlightening, on this.

**Comment by cjschroder** [comment]
https://github.com/SUSE/doc-cap/pull/128
