### ISSUE TITLE
Change for "Backup and Restore" - Buildpacks

### ISSUE THREAD

**Issue by svollath** [SUSE/doc-cap#133]
With cf-backup-plugin-1.0.7 and 1.0.8-pre apps don't fail, but simply need the custom buildpack to be in place before they are restored. I also thought that for buildpacks itself it's not about backup/restore, but more about managing them - e.g. restoring an app using a custom buildpack of a newer version should work fine.

Therfore we should replace:

"Buildpacks are not saved. Attempts to restore applications using buildpacks not available on the target SUSE Cloud Foundry instance will fail. Saving and restoring buildpacks has to be performed separately, and restoration completed before the backup plugin is invoked."

by something like:

"Buildpacks are not saved. Applications using e.g. custom buildpacks not
available on the target SUSE Cloud Foundry instance will not get restored.
Custom buildpacks have to be managed separately, and relevant buildpacks
need to be in place before affected applications are restored."

**Comment by cjschroder** [comment]
Thanks @svollath https://github.com/SUSE/doc-cap/commit/918037602b28c0b8a2ce6555e0f612892c868f3f
