### ISSUE TITLE
Helm upgrade commands need the `--recreate-pods` flag

### ISSUE THREAD

**Issue by viovanov** [SUSE/doc-cap#145]
We need to document the need for the `--recreate-pods` when doing `helm upgrade` commands.

> Important: **This only applies to upgrades from one version to another.**

**Comment by btat** [comment]
PR https://github.com/SUSE/doc-cap/pull/155

**Comment by cjschroder** [comment]
@btat you can close issues that you resolve. Thanks, much appreciate your work.

**Comment by btat** [comment]
Closing as PR #155 is merged.
