### ISSUE TITLE
Change docs for AKS due to AKS clusters now using RBAC by default

### ISSUE THREAD

**Issue by HartS** [SUSE/doc-cap#146]
From https://trello.com/c/5O8lVVNS/495-change-aks-docs-to-assume-the-cluster-has-rbac-enabled

According to https://github.com/Azure/AKS/issues/67, AKS now enables RBAC on all AKS clusters deployed (unless the `--disable-rbac` option is used during creation). This means AKS clusters deployed with standard options will have RBAC enabled, so our documentation now needs to reference the PSP workaround for AKS deployments.

In addition to the PSP workaround, https://github.com/SUSE/doc-cap/blob/0abcfcb1b348be5f78a895901b1501318ff9117f/xml/cap_depl_azure.xml#L558 should now be `auth: rbac` instead of `auth: none`

**Comment by cjschroder** [comment]
Still needs review, closing as PR has been merged. https://github.com/SUSE/doc-cap/pull/157
