### ISSUE TITLE
Stratos URL needs to match DOMAIN used

### ISSUE THREAD

**Issue by HartS** [SUSE/doc-cap#150]
From the docs:

> In this example, pointing your web browser to https://10.10.100.82:8443 opens the console

If you just use the IP, you get a `domain mismatch` page. For example, even though the external IP for my deployment was `10.84.101.210`, I had to use `10.84.101.210.omg.howdoi.website` because that was the `DOMAIN` specified in my `scf-config-values.yaml` (which is used as the values file when helm installing stratos).

**Comment by btat** [comment]
Addressed by PR https://github.com/SUSE/doc-cap/pull/156

**Comment by cjschroder** [comment]
You're right that the domain needs to match in scf-config-values.yaml. The example scf-config-values.yaml uses example.com.

**Comment by btat** [comment]
Closing as PR #156 is merged
