### ISSUE TITLE
Update AKS deploy instructions to include another parameter for disk size

### ISSUE THREAD

**Issue by gaktive** [SUSE/doc-cap#151]
Azure's AKS has a couple issues that require us to expand the root partition of the main image.

The docs should be updated to reflect that `--node-osdisk-size=60` should be added to the length `az aks create` command when deploying on AKS under 10.2 _Create Resource Group and AKS Instance_ in the Deployment Guide:

> Create a new AKS managed cluster:

`tux > az aks create --resource-group $RGNAME --name $AKSNAME \
 --node-count $NODECOUNT --admin-username $ADMINUSERNAME \
 --ssh-key-value $SSHKEYVALUE --node-vm-size $NODEVMSIZE`

should now read:

> Create a new AKS managed cluster:

`tux > az aks create --resource-group $RGNAME --name $AKSNAME \
 --node-count $NODECOUNT --admin-username $ADMINUSERNAME \
 --ssh-key-value $SSHKEYVALUE --node-vm-size $NODEVMSIZE --node-osdisk-size=60`

**Comment by btat** [comment]
Closing as PR #168 has been merged
