### ISSUE TITLE
PSP support now available for fissile and role manifests

### ISSUE THREAD

**Issue by gaktive** [SUSE/doc-cap#166]
There's been a change tied to PSPS support whereby in the past, security policies allow everything.  This has been changed to only allow diego-cell, nfs-broker, and (until upstream exposes a changed gorouter SSL port) router roles to be privileged.

https://trello.com/c/9EmTR4JL/775-3-add-psp-support-to-fissile-and-role-manifests#

**Comment by gaktive** [comment]
More information is here tied to the updated AZ patches for diego: https://trello.com/c/UXZXgy8V/843-patch-diego-cells-so-they-respond-to-az

There's an associated wiki page that gets more in-depth: https://github.com/SUSE/cloudfoundry/wiki/Patching-cells-so-they-respond-to-AZ

**Comment by btat** [comment]
Adding below to PSP was found to be an alternative since the content for this issue has was on documented yet.

```
- kind: ServiceAccount
  name: default-privileged
  namespace: scf
- kind: ServiceAccount
  name: node-reader
  namespace: scf
```
