### ISSUE TITLE
yaml spacing off on suse.com docs

### ISSUE THREAD

**Issue by abonillasuse** [SUSE/doc-cap#179]
the spacing of the certificate lines are wrong at line UAA_CA_CERT: | in 7.3 of the docs

it is also off in the values.yaml in 7.6

**Comment by cjschroder** [comment]
Please review @abonillasuse, thanks!
https://github.com/SUSE/doc-cap/pull/183

**Comment by abonillasuse** [comment]
looks OK

**Comment by btat** [comment]
Resolved by #183 which has been merged
