### ISSUE TITLE
Minibroker

### ISSUE THREAD

**Issue by gaktive** [SUSE/doc-cap#196]
Minibroker is a project that allows external services to exist as containers on a Kubernetes cluster, which can be deployed via Helm.

Details on Minibroker including how to run it: https://github.com/osbkit/minibroker

Already working in CAP 1.2.1 is Redis. Details on setup here:
https://trello.com/c/7fHQPF6S/459-5-service-broker-investigation-minibroker

Work on expanding Minibroker support to other services like MariaDB, Mongo, Mysql and Postgres are described here, which is intended for 1.3: https://trello.com/c/HME5FDZw/806-minibroker-for-other-services

Steps for those are mostly identical to Redis though MariaDB will require an additional parameter.

**Comment by troytop** [comment]
https://github.com/SUSE/cloudfoundry/wiki/Using-the-minibroker-with-SUSE-CAP

**Comment by troytop** [comment]
Note on postgresql and mariadb: By default Minibroker creates server instances *without* a named database. However, you can pass arguments to create databases with the `-c` option for `create-services`. For example:

    cf create-service postgresql 9-6-2 djangocms-db -c '{"postgresDatabase":"mydjango"}'

Or:

    cf create-service mariadb 10-1-34 my-db  -c '{"mariadbDatabase":"arbitraryname"}'
 
Other options can be set too, but vary by database type. The ones above are critical for normal usage though.

**Comment by gaktive** [comment]
QA is testing out the Minibroker helm charts, which will simplify deployment once verified.
