### ISSUE TITLE
change creating Tiller service to config file

### ISSUE THREAD

**Issue by cjschroder** [SUSE/doc-cap#211]
Use a yaml file instead of running commands, like http://docserv.nue.suse.com/documents/CAP_1/cap-deployment/single-html/#sec.cap.eks-helm

http://docserv.nue.suse.com/documents/CAP_1/cap-deployment/single-html/#sec.cap.tiller-service

**Comment by btat** [comment]
@cjschroder since https://github.com/SUSE/doc cap/commit/18a447447bfe130d153a39c5a009a9bed5bd8da6 has been merged, can we go ahead and chose this issue?

**Comment by cjschroder** [comment]
Yes.
