### ISSUE TITLE
PR #210 typos and other things

### ISSUE THREAD

**Issue by andreas-kupries** [SUSE/doc-cap#212]
## References

- https://trello.com/c/ZDONmg5O/856-please-review-numerous-corrections-and-updates-210-ms-azure-chapter-deployment-guide
- https://github.com/SUSE/doc-cap/pull/210
- http://docserv.nue.suse.com/documents/CAP_1/cap-deployment/single-html/#cha.cap.depl-azure

#### http://docserv.nue.suse.com/documents/CAP_1/cap-deployment/single-html/#sec.cap.create-aks-instance
- `The following example changes it to aks-mypool: `
   The example code immediately after actually uses `mypool`, without `aks-` prefix.

#### http://docserv.nue.suse.com/documents/CAP_1/cap-deployment/single-html/#sec.cap.swap-accounting

- `awk '{print$1}'` - Adding a space between `print` and `$1` might be more readable. (It is not a bug, I checked, and the code does work without the space).
- There are references to `mypool`, which might have to be `aks-mypool` ?! (Or `aks-nodepool` as the default to replace ?)

#### http://docserv.nue.suse.com/documents/CAP_1/cap-deployment/single-html/#sec.cap.tiller-service

Phrasing confused me at first, talking about `service` and then creating a `service account` as the first command. Further reading made it clear that you are creating both the service and the service account for it. Maybe mention both in title and intro sentence.

**Comment by cjschroder** [comment]
Thank you both, I appreciate the attention to detail.
https://github.com/SUSE/doc-cap/pull/215

**Comment by cjschroder** [comment]
re mypool / aks-mypool, the only bit that users control is the part represented by 'mypool'. Hopefully the text makes that clear.

**Comment by satadruroy** [comment]
Here's another refinement: the resource group where the AKS nodes are deployed can be discovered via the following command, i.e., in 

http://docserv.nue.suse.com/documents/CAP_1/cap-deployment/single-html/#sec.cap.swap-accounting

1. `export MCRGNAME=$(az aks show --resource-group $RGNAME --name $AKSNAME --query nodeResourceGroup -o json | jq -r '.')`

This way we won't have to rely on any naming convention used by Azure.

**Comment by HartS** [comment]
@satadruroy I just tried the suggestion above and I'm actually not seeing the `MC_...` RG name in the output from that command

**Comment by satadruroy** [comment]
Works for me:
`az aks show -g sroy-cap-aks -n cap-cluster --query nodeResourceGroup -o json | jq -r '.'
MC_sroy-cap-aks_cap-cluster_eastus`
