### ISSUE TITLE
Use full name of option in example commands

### ISSUE THREAD

**Issue by btat** [SUSE/doc-cap#213]
Currently some examples (e.g. `kubectl create -f` should be `kubectl create --filename`) use the shorthand name of an option/flag. Using the full name of the flag in some cases will provide better readability and the commands will be self-explanatory. 

Includes, but not limited to:
- `az provider list | egrep -w`
- `az vm list -o`
- `az vm restart -g -n`
- `curl -k`
- `docker run -it -v`
- `helm search -l`
- `kubectl create -f` => `--filename`
- `kubectl exec -it`
- `kubectl -o` => `--output`
- `sed -i -r`
- `uaac token client get admin -s password` => `--secret`
- `uaac curl -X -k -H -d`
- `watch -c` => `--color`

**Comment by cjschroder** [comment]
Good idea :+1:

**Comment by cjschroder** [comment]
Someday it would be good to go back and fix old text. Until then do this for new content.
