### ISSUE TITLE
Mysql sidecar version compatibility note

### ISSUE THREAD

**Issue by gaktive** [SUSE/doc-cap#223]
There's an advisory buried within the MySQL sidecar instructions about version numbers higher than 8.0.3 that require an extra parameter to get a connection to the database: https://github.com/SUSE/cf-usb-sidecar/tree/develop/csm-extensions/services/dev-mysql#mysql-version-compatibility-note

We may have to put this somewhere in the deployment guide for more attention. Low priority.

**Comment by btat** [comment]
Closed via #263
