### ISSUE TITLE
User Guide

### ISSUE THREAD

**Issue by btat** [SUSE/doc-cap#229]

**Comment by cjschroder** [comment]
Right, and while we're at it let's use our abundant time and resources to create an Admin Guide as well.  :stuck_out_tongue_closed_eyes:

We need both of these, sigh.

**Comment by btat** [comment]
The app troubleshooting didn't really fit in our deployment guide so I needed something to put them under. That and I wanted to play with the create epic button hehe :D

**Comment by cjschroder** [comment]
Then you might as well go for it! The boilerplate stuff alone fills a lot of pages :)

**Comment by cjschroder** [comment]
These should satisfy this issue: https://github.com/SUSE/doc-cap/pull/255, https://github.com/SUSE/doc-cap/commit/b16f6de504dac3dfb4e08b2805afd280dbd8622d
