### ISSUE TITLE
Run verification test suite after new deployments of CAP

### ISSUE THREAD

**Issue by btat** [SUSE/doc-cap#230]
Add advisory message and instructions on how to run the smoke test.

See https://bugzilla.suse.com/show_bug.cgi?id=1117087 for background.

**Comment by mook-as** [comment]
@troytop Do we want to actually ship the smoke tests then? It isn't in the [chart](https://github.com/SUSE/kubernetes-charts-suse-com/tree/master/stable/cf/templates). If yes, we could do it as a [helm test](https://docs.helm.sh/developing_charts/#chart-tests), perhaps?

**Comment by cjschroder** [comment]
I'm wondering about this as well-- smoke tests sound good for customer use, as long they don't create additional problems, and are packaged in a nice friendly way.

**Comment by btat** [comment]
Marking as blocked for now as the tests are currently not available for customer use.

**Comment by HartS** [comment]
The smoke tests in the SCF releases will work for both SCF and CAP. Even though we haven't released CAP smoke tests yet, we should advise customers to run the ones from the SCF release while we wait for these. The following script will automate the entire process of getting the SCF release URL, picking out the smoke-tests file, substituting the necessary values, and creating the smoke-tests as a pod, which the user can then follow and delete. I think this can be transformed into documentation which would give the user the necessary information to do it themselves, but we can provide the script as a reference as well.
```
set -o errexit -o nounset

CAP_RELEASE_VERSION=${CAP_RELEASE_VERSION:-2.14.5}
CF_NAMESPACE=${CF_NAMESPACE:-scf}
# Exit with error if an expected cli is missing
type jq unzip kubectl >/dev/null
DOMAIN=$(kubectl get pods -o json --namespace "${CF_NAMESPACE}" ${api_pod_name} | jq -r '.spec.containers[0].env[] | select(.name == "DOMAIN").value')
echo "Using SUSE Cloud Foundry release $CAP_RELEASE_VERSION in namespace $CF_NAMESPACE with domain $DOMAIN"
cleanup() {
  TMPDIR=${PWD##/tmp/tmp.}
  rm -r "/tmp/tmp.${TMPDIR##/tmp/tmp.}"
}
cd $(mktemp -d)
trap cleanup EXIT
curl -sLO $(curl -sL "https://api.github.com/repos/SUSE/scf/releases" | jq -r ".[] | select(.tag_name == \"$CAP_RELEASE_VERSION\").assets[0].browser_download_url")
unzip -j *.zip kube/cf-opensuse/bosh-task/smoke-tests.yaml

# Get the name of the CF generated secret which contains MONIT_PASSWORD
generated_secrets_secret="$(kubectl get pod api-group-0 --namespace "${CF_NAMESPACE}" -o jsonpath='{@.spec.containers[0].env[?(@.name=="MONIT_PASSWORD")].valueFrom.secretKeyRef.name}')"

# Replace the name of the generated secret reference in the smoke test manifest
# You'll see a section that looks like:
# And replace 'secrets' with the appropriate generated secret name
AWK_SCRIPT='
/^    - name: "MONIT_PASSWORD"$/ {
  print;
  print "      valueFrom:\n        secretKeyRef:\n          key: \"monit-password\"\n          name: \"'${generated_secrets_secret}'\"";
  monit_password=1
  next
}
( monit_password==1 && /^    -/ ) {
  monit_password=0
}
monit_password == 0 {
  print
}'
awk "${AWK_SCRIPT}" smoke-tests.yaml > smoke-tests-updated.yml
sed -i "s/cf-dev\\.io/$DOMAIN/g" smoke-tests-updated.yaml
kubectl create --namespace $CF_NAMESPACE -f smoke-tests-updated.yml
echo -e "  Check smoke tests status with\nkubectl get pod -n $CF_NAMESPACE smoke-tests\n  or\nkubectl describe pod -n $CF_NAMESPACE smoke-tests"
echo -e "  Once started, you can follow the smoke test logs with\nkubectl logs -f -n $CF_NAMESPACE smoke-tests"
echo -e "  Upon completion, you can delete the completed pod with\nkubectl delete pod -n $CF_NAMESPACE smoke-tests"
```

**Comment by btat** [comment]
Based on discussions around messaging involved with doing this, going to mark this as blocked until there's more clarity on how to proceed.

**Comment by troytop** [comment]
What we really need is a verification section which is referenced from critical points in the installation guide. Instead of a full QA smoke test, run specific (optional) tests manually to check that each point in the installation produces a working result.

**Comment by troytop** [comment]
Need a new series of tests for customers or field to run which are actually helpful in that context (i.e. not in QA). The tests need to indicate what might be misconfigured and provide some clues as to what needs to be fixed.

**Comment by gaktive** [comment]
Closing in light of upcoming kubecf in CAP 2.0, which will likely reset what we need to consider here.
