### ISSUE TITLE
1.3 CAP: change in url of service broker

### ISSUE THREAD

**Issue by prabalsharma** [SUSE/doc-cap#233]
Change to usb url from `https://cf-usb.scf.svc.cluster.local:24054` in CAP 1.2.1 to `https://cf-usb-cf-usb.scf.svc.cluster.local:24054` in CAP 1.3

Workaround required post upgrade to CAP 1.3:
``` cf update-service-broker usb broker-admin "$(kubectl get secret secrets-2.14.5-1 --namespace scf -o yaml | grep \\scf-usb-password: | cut -d: -f2 | base64 -id)" https://cf-usb-cf-usb.scf.svc.cluster.local:24054```

https://bugzilla.suse.com/show_bug.cgi?id=1117202

**Comment by gaktive** [comment]
This will be included in the release notes. We may fix this in SCF whereby what was originally documented will be true again but for the upgrade from 1.2.1 to 1.3, this is required.
