### ISSUE TITLE
Boost Azure instance type to Standard_D4_v2

### ISSUE THREAD

**Issue by gaktive** [SUSE/doc-cap#238]
In the Azure deployment guide, we refer to `Standard_D2_v2` as the sample instance size to deploy CAP. Based on the increase in footprint with 1.3, we should cite `Standard_D4_v2` or higher as App Autoscaler and Credhub require more space than the previously cited instance size can handle. It brings us in line with the other platform flavours too.

**Comment by btat** [comment]
Reopening in case more work needs to be done based on https://trello.com/c/rE6BnKWm/542-determine-why-does-cap-13-needs-bigger-instance-sizes-to-run-on-aks

**Comment by gaktive** [comment]
Based on QA's investigation, D4_v2 has proven to be the way to go, so we'll stick with that for now. They'll look at enabling some memory options to track usage and based on their findings, they may open new tickets.

**Comment by btat** [comment]
@gaktive #239 has been merged. Does more work need to be done for this?

**Comment by gaktive** [comment]
For now, no. We'll file new items as needed. Important thing is to ensure no one using AKS tries D2 anymore. Thanks!
