### ISSUE TITLE
Always install to a fresh namespace to prevent reusing stale secrets

### ISSUE THREAD

**Issue by troytop** [SUSE/doc-cap#243]
Need to document that `helm delete --purge ...` does _not_ remove secrets. Reinstalling to an old namespace can cause stale secrets to be reused when pods start, while the secret generation scripts are still running.

This applies to all deployment targets. Fully clean up old uaa and scf deployments by running `kubectl delete ns $namespace` before deploying uaa or scf to the same $namespace.

**Comment by btat** [comment]
@troytop We currently have this section https://www.suse.com/documentation/cloud-application-platform-1/singlehtml/book_cap_deployment/book_cap_deployment.html#sec.cap.rebuild.depl, should we have this in more areas to bring attention to it?

**Comment by cjschroder** [comment]
right, I thought that the steps in that section made a clean and complete deletion.
