### ISSUE TITLE
Configure the SUSE Cloud Application Platform Production Deployment

### ISSUE THREAD

**Issue by tgeek77** [SUSE/doc-cap#246]
2.4  Configure the SUSE Cloud Application Platform Production Deployment

https://www.suse.com/documentation/cloud-application-platform-1/singlehtml/book_cap_deployment/book_cap_deployment.html#sec.cap.configure-prod

cap-psp-rbac.yaml in the instructions is now incorrect.  See http://mailman.suse.de/mlarch/SuSE/paas-devel/2018/paas-devel.2018.11/msg00118.html

Without the updated clusterrolebinding, not all statefulsets will start and will fail with the error:

create Pod router-0 in StatefulSet router failed error: pods "router-0" is forbidden: unable to validate against any pod security policy: [spec.containers[0].securityContext.allowPrivilegeEscalation: Invalid value: true: Allowing privilege escalation for containers is not allowed]

**Comment by cjschroder** [comment]
Thanks @tgeek77, appreciate the information.

**Comment by btat** [comment]
Going to close this as #247 will handle the ClusterRoleBinding/ServiceAccount bits via:

```
psp:
        nonprivileged: "suse.cap.psp"
        privileged: "suse.cap.psp"
```
