### ISSUE TITLE
Create Resource Group and AKS Instance

### ISSUE THREAD

**Issue by petersatsuse** [SUSE/doc-cap#250]
13.2  Create Resource Group and AKS Instance

https://susedoc.github.io/doc-cap/develop/cap-deployment/html/cha.cap.depl-azure.html#sec.cap.create-aks-instance

MSFT approached us to include a GUID for usage count of CAP into the documentation.
As we do not have a template for CAP in the Azure Marketplace we need to hand over this as environment variable. See
https://docs.microsoft.com/en-us/azure/marketplace/azure-partner-customer-usage-attribution
So simply like below 
````
export SUSE_CAP_ID='pid-12345678-1234-abcd-efgh-12345678901'
````

**Comment by cjschroder** [comment]
Thanks @petersatsuse. This looks bigger than a documentation issue, I will discuss it with the CAP team.

**Comment by cjschroder** [comment]
See the paas-devel list if you're interested.

**Comment by mook-as** [comment]
I can't see anything on [that page](https://docs.microsoft.com/en-us/azure/marketplace/azure-partner-customer-usage-attribution) about environment variables, or how to use it in conjunction with AKS. It looks like if we actually used the Azure APIs (which as far as I know we don't), we'd embed the tracking in there.

**Comment by petersatsuse** [comment]
Am 06.12.2018 um 18:54 schrieb Mark Yen:
>
> > I can't see anything on that page 
> <https://docs.microsoft.com/en-us/azure/marketplace/azure-partner-customer-usage-attribution> 
> about environment variables, or how to use it in conjunction with AKS.
>

The page shows a example - which is the way MSFT has requested to do for CAP

--snip--


        Tag a deployment by using the Azure CLI

When you use the Azure CLI to append your GUID, set 
the*AZURE_HTTP_USER_AGENT*environment variable. You can set this 
variable within the scope of a script. You can also set the variable 
globally for shell scope:

Copy

|export AZURE_HTTP_USER_AGENT='pid-eb7927c8-dd66-43e1-b0cf-c346a422063'|

--snip--

 > It looks like if we actually used the Azure APIs (which as far as I 
know we don't), we'd embed the tracking in there.

Nop. The tracking is for us as SUSE, in order to get usage count through 
the MSFT Azure tooling.

This is in the meantime mandatory for all our offerings on Azure.

cu

Peter

**Comment by troytop** [comment]
@petersatsuse please contact CAP product management about this, as it requires discussion and engineering oversight. It's not a straightforward docs change.
