### ISSUE TITLE
[doc] 5.2.2  Enable Custom Availability Zone Information Handling

### ISSUE THREAD

**Issue by berchtos** [SUSE/doc-cap#257]
5.2.2  Enable Custom Availability Zone Information Handling

https://www.suse.com/documentation/cloud-application-platform-1/singlehtml/book_cap_deployment/book_cap_deployment.html#sec.cap.enable-custom-availability-zone-handling

The instructions lack of information, that the `node-reader` service account requires permissions to read the node labels as per this part of the script: https://github.com/SUSE/scf/blob/2.14.5/container-host-files/etc/scf/config/scripts/configure-az.sh#L26

Manually executing the script basically demonstrates the problem:

```
diego-cell/0:/opt/fissile/startup/scripts# ./configure-az.sh
AZ: Configured cf-az-label
AZ: Node...... node1
Error from server (Forbidden): nodes "node1" is forbidden: User "system:serviceaccount:scf:node-reader" cannot get nodes at the cluster scope
AZ: No information found
AZ: Skipping
```

After granting the service account read permissions for the nodes, the script works.

**Comment by cjschroder** [comment]
Hi @berchtos, thanks for reporting this. This could be a PSP issue, did you apply the cap-psp-rbac.yaml configuration file in https://www.suse.com/documentation/cloud-application-platform-1/singlehtml/book_cap_deployment/book_cap_deployment.html#sec.cap.caasp-3 ? That should automatically give node-reader the correct permissions. 

(This may need some clarification in the manual, we assume the user has completed all the previous deployment steps)

**Comment by mook-as** [comment]
Ah, interesting, https://github.com/SUSE/scf/commit/67ddc6cac9e3680289f13ca2f3e66e273cfb8afd says we should document that, but we (and specifically me since I did the merge) forgot to ensure the proper documentation. Sorry!

@cjschroder Do you think there's enough digestible information in [Andreas' docs](https://trello-attachments.s3.amazonaws.com/58e56a9ad28527ae93715837/5bc8bec26747b78dfcb70c9f/d0a5bae3eef7f4d67d60b51dd07724d8/nrp.md) to put this in the deployment guide?  That's also possible as a pair of commands if that seems better:

```bash
kubectl create clusterrole node-reader-clusterrole --verb=get,list,watch --resource=nodes
kubectl create clusterrolebinding node-reader-node-reader-clusterrole-binding --serviceaccount=${NAMESPACE}:node-reader --clusterrole node-reader-clusterrole
```
(The namespace needs to be replaced of course)

**Comment by btat** [comment]
@mook-as Now that there's https://trello.com/c/9EmTR4JL/775-3-add-psp-support-to-fissile-and-role-manifests & https://github.com/SUSE/kubernetes-charts-suse-com/blob/master/stable/cf/templates/diego-cell.yaml#L39 doesn't that automatically takes care of the CR/CRB/SA bits when the PSPs are assigned through the below?

```
kube:
  psp:
    nonprivileged: ~
    privileged: ~
```

**Comment by mook-as** [comment]
Good point, no that does not take care of the necessary bits for this (even though it involves CR/CRBs).  We might want to make sure what we do ends up (for defaulting PSP/CR/CRBs) covers this too, even though this doesn't touch PSPs.
