### ISSUE TITLE
Adding capacity (Kubernetes nodes and Diego cells)

### ISSUE THREAD

**Issue by troytop** [SUSE/doc-cap#265]
Need a section on how to expand CAP in place. 

Basically, this is done by adding nodes to the Kubernetes, updating the diego_cell count in values.yaml, and then running a `helm upgrade ...`

**Comment by btat** [comment]
https://docs.microsoft.com/en-us/azure/aks/scale-cluster

**Comment by gaktive** [comment]
Sounds like only EKS is missing then?

**Comment by btat** [comment]
> Sounds like only EKS is missing then?

Yes. Originally the plan was to use eksctl since adding a node is a single command, but Satadru and I were hitting all sorts of permission issues when we tried eksctl. Will see if I can sort out the permission stuff, otherwise we can just use the old style.
