### ISSUE TITLE
Warn that helm rollback is not supported

### ISSUE THREAD

**Issue by troytop** [SUSE/doc-cap#270]
Paraphrasing from the internal mailing list:

`helm rollback` is not supported and can potentially break your cluster completely. Database migrations only run forward and cannot be undone.

Unfortunately this is only mentioned in an XML comment in the docs:

 https://github.com/SUSE/doc-cap/blob/b16f6de/xml/cap_admin_upgrade.xml#L18-L19

Database schema can change over time. During upgrades both pods of the current and the next release may run concurrently, so the schema must stay compatible with the immediately previous release. But this will no longer be true for later upgrades.

It’s not supported because Cloud Foundry doesn’t support it. To address such a situation, a full raw data backup and restore would be required instead of a rollback.

**Comment by cjschroder** [comment]
closing for https://github.com/SUSE/doc-cap/commit/2e5d85949930d31922322a570f2232f6f0ce381f
