### ISSUE TITLE
Update auth:rbac in values.yaml

### ISSUE THREAD

**Issue by btat** [SUSE/doc-cap#272]
In the changelog of SCF it states `Make RBAC the default in the values.yaml (no need to specify anymore)`

Verify if this is still required in the scf-config-values.yaml examples

https://github.com/SUSE/scf/blob/f725a4d45f24d1aa328d1d766e7e3af803e8441a/CHANGELOG.md#changed-23

**Comment by cjschroder** [comment]
It's there:
```
helm inspect suse/cf-opensuse|grep -n rbac
29:  auth: "rbac"
```
https://github.com/SUSE/doc-cap/pull/278 removes it from the example scf-config-values.yaml file
