### ISSUE TITLE
[doc] 17.2  Create hostpath Storage Class

### ISSUE THREAD

**Issue by lcavajani** [SUSE/doc-cap#281]
17.2  Create hostpath Storage Class

https://www.suse.com/documentation/cloud-application-platform-1/singlehtml/book_cap_deployment/book_cap_deployment.html#sec.cap.storageclass

You should add a warning for CaaSP explaining that if a node is added/removed to the cluster or if a node update is started from Velum, these changes will be overwritten by the salt orchestration which will reconfigure ``kube-controller-manager`` service to its original state.

**Comment by cjschroder** [comment]
thanks @lcavajani -- we've gotten so many warnings about the limitations of hostpath we removed all mentions of it. Current CAP Guides drafts are always on http://docserv.nue.suse.com/documents/. We'll publish to suse.com/documentation in the next few days.
