### ISSUE TITLE
Deploy Stratos on EKS

### ISSUE THREAD

**Issue by btat** [SUSE/doc-cap#282]
There's currently no information on how this is done.

During testing by Prabal he is hitting https://bugzilla.suse.com/show_bug.cgi?id=1117173&GoAheadAndLogIn=1

**Comment by btat** [comment]
See https://trello.com/c/RmRzb0uy/735-aws-loadbalancer for tested steps

**Comment by gaktive** [comment]
We're starting to see more problems from the field on getting Stratos working on EKS so we should boost priority on this.

**Comment by cjschroder** [comment]
We need a reliable, detailed source document that spells out all the steps in order, and that does not use omg.howdoi.website.

**Comment by gaktive** [comment]
According to Neil, only one storage class is needed after all, so we'll need to straighten out the requirements before documenting.

**Comment by prabalsharma** [comment]
> Need 2 storage classes
> 
> See https://github.com/SUSE/stratos/blob/v2-master/docs/eksdeployment.md.

its just 1 SC. The doc just shows the default SC but it not used any where. Take a look at the QA card you added, it also uses only 1 SC (same as this doc link)

**Comment by prabalsharma** [comment]
> We need a reliable, detailed source document that spells out all the steps in order, and that does not use omg.howdoi.website.

where did you see omg.howdoi.website?
The QA card referenced by Billy for detailed test steps uses LB setup on EKS. It uses `aws.howdoi.website` which is a real domain, in Route 53.

**Comment by btat** [comment]
> > Need 2 storage classes
> > See https://github.com/SUSE/stratos/blob/v2-master/docs/eksdeployment.md.
> 
> @btat @gaktive its just 1 SC. The doc just shows the default SC but it not used any where. Take a look at the QA card added by Billy, it also uses only 1 SC (same as this doc link).

Good to know. I think the idea came from the first sentence starting with `Two storage classes are required, one general storage class...` in https://github.com/SUSE/stratos/blob/v2-master/docs/eksdeployment.md#storage-classes

**Comment by prabalsharma** [comment]
Stratos on EKS: 
1. kubeclt create -f scoped_storage_class.yaml

scoped_storage_class.yaml:

```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: gp2scoped
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  zone: "us-west-2a"
reclaimPolicy: Retain
mountOptions:
  - debug
```

Its important to NOTE that its zone which has suffix like `a` or `b` and NOT JUST us-west-2. I have used: `a`
Just double check, with k get sc. Now you will see 2:
> k get sc
kubectl get sc
NAME            PROVISIONER             AGE
gp2 (default)   kubernetes.io/aws-ebs   44d
gp2scoped       kubernetes.io/aws-ebs   42d

2. 
`helm install suse/console --set kube.storage_class.persistent=gp2scoped --set services.loadbalanced=true --namespace=console --name console`

3.
get EXTERNAL_IP (LB url) from: kubectl get svc -n console console-ui-ext -o wide
OR kubectl get svc -n console console-ext -o wide
(depends on stratos version)

Use this LB url to create a CNAME record in Route53.
