### ISSUE TITLE
Please document release name length limits

### ISSUE THREAD

**Issue by mook-as** [SUSE/doc-cap#292]
Hi!

I'm looking at the maximum lengths for things we support (in 1.3.1., once https://github.com/cloudfoundry-incubator/fissile/pull/465 and matching SCF PR lands).  So far, I've got:
- UAA: 53 characters (limitation of helm release names, as in `helm install <name>`)
- SCF: 36 characters (limitation of the UAA identity zone, see https://github.com/cloudfoundry/uaa/blob/develop/docs/UAA-APIs.rst#identity-zone-management-apis)

Note that I'm doing `helm install <name> --namespace <name>`, so it's effectively the smaller of the two here.

**Comment by cjschroder** [comment]
Thanks @mook-as. Out of curiousity, is there a reason to even want names longer than 36 chars?

**Comment by mook-as** [comment]
Not that I'm aware of, but I assume customers like to do crazy things :)  It's perfectly reasonable to just say we don't support anything more than 36.
