### ISSUE TITLE
[doc] 7.9  Configuring and Testing the Native Microsoft AKS Service Broker

### ISSUE THREAD

**Issue by PeterAnderssonSUSE** [SUSE/doc-cap#294]
7.9  Configuring and Testing the Native Microsoft AKS Service Broker

https://www.suse.com/documentation/cloud-application-platform-1/singlehtml/book_cap_guides/book_cap_guides.html#sec.cap.azure-service-broker

Please be consistent
$AZURE_SUBSCRIPTION_ID is the same as $SUBSCRIPTION_ID=

**Comment by btat** [comment]
Inconsistent naming in section as well. Moved example to #293
