### ISSUE TITLE
Document `services:loadBalanced=true` param for AKS

### ISSUE THREAD

**Issue by cjschroder** [SUSE/doc-cap#298]
This is too complex and error-prone. It requires setting and re-setting IP addresses and too much DNS finicking. The existing documented steps for creating a load balancer on AKS are simpler and reliable. Marking as blocked until the process is more refined.

Refs:
https://github.com/SUSE/cloudfoundry/wiki/Load-balancers-in-Azure-AKS
https://trello.com/c/rEQ2SmHi/796-load-balancer-improve-docs

**Comment by cjschroder** [comment]
replaces https://github.com/SUSE/doc-cap/issues/73

**Comment by cjschroder** [comment]
@satadruroy this is blocked until I receive a reliable, authoritative howto from engineering.

**Comment by satadruroy** [comment]
Ok, I got it to work so I'll work on this one.

**Comment by cjschroder** [comment]
wonderful, thanks @satadruroy. It doesn't have to be pretty, just a list of all the steps that customers need to do this.

**Comment by satadruroy** [comment]
https://github.com/SUSE/cloudfoundry/wiki/Deploying-CAP-on-AKS

**Comment by cjschroder** [comment]
Thanks @satadruroy. It still looks too complex, but I'll give it a go :)
