### ISSUE TITLE
document Amazon EKS load balancer

### ISSUE THREAD

**Issue by cjschroder** [SUSE/doc-cap#299]
https://github.com/SUSE/cloudfoundry/wiki/Load-balancers-in-AWS-EKS

**Comment by cjschroder** [comment]
replaces https://github.com/SUSE/doc-cap/issues/73

**Comment by cjschroder** [comment]
updated doc:
https://github.com/SUSE/scf/wiki/Deployment-on-Amazon-EKS

**Comment by satadruroy** [comment]
More up-to-date instructions are available here: https://github.com/SUSE/cloudfoundry/wiki/Load-balancers-in-AWS-EKS
