### ISSUE TITLE
AKS Service Broker duplicate cf create-service-broker command

### ISSUE THREAD

**Issue by PeterAnderssonSUSE** [SUSE/doc-cap#301]
7.9  Configuring and Testing the Native Microsoft AKS Service Broker

https://www.suse.com/documentation/cloud-application-platform-1/singlehtml/book_cap_guides/book_cap_guides.html#sec.cap.azure-service-broker

The command:
cf create-service-broker azure $(kubectl get deployment osba-open-service-broker-azure \
--namespace osba -o jsonpath='{.spec.template.spec.containers[0].env[?(@.name == "BASIC_AUTH_USERNAME")].value}') $(kubectl get secret --namespace osba osba-open-service-broker-azure -o jsonpath='{.data.basic-auth-password}' | base64 -d) http://osba-open-service-broker-azure.osba

Is runned twice, the second time is not needed

**Comment by cjschroder** [comment]
Thanks @PeterAnderssonSUSE, would you review the PR? https://github.com/SUSE/doc-cap/pull/302
