### ISSUE TITLE
Document that (for custom PSPs) they should specify `SYS_RESOURCE` in added capabilities

### ISSUE THREAD

**Issue by btat** [SUSE/doc-cap#303]
https://trello.com/c/5ejfb8Ok/907-document-that-for-custom-psps-they-should-specify-sysresource-in-added-capabilities

**Comment by btat** [comment]
@satadruroy @gaktive in https://github.com/SUSE/doc-cap/pull/278 @cjschroder updated the instructions steps after deploying to an upgraded CaasSP 3 without `SYS_RESOURCE`. The PR was made in Jan 2019 and the linked card  in the description was created in Dec 2018. Do you know if it's been determined that this requirement is still needed?

**Comment by satadruroy** [comment]
Good catch, @btat - this should no longer be needed from 1.3.1
