### ISSUE TITLE
AKS Service Broker curl example does not work and better example app required

### ISSUE THREAD

**Issue by PeterAnderssonSUSE** [SUSE/doc-cap#304]
7.9  Configuring and Testing the Native Microsoft AKS Service Broker

https://www.suse.com/documentation/cloud-application-platform-1/singlehtml/book_cap_guides/book_cap_guides.html#sec.cap.azure-service-broker

The curl command at the end do not work, this is what I get:
curl scf-rails-example.cap.suselinux.info
<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx/1.14.0</center>
</body>
</html>

This command works for me:
curl -k https://scf-rails-example.cap.suselinux.info
<!DOCTYPE html>
<html>
  <head>
    <title>ScfRailsExample</title>
    <meta name="csrf-param" content="authenticity_token" />
<meta name="csrf-token" content="UvrSADyjd34Jf3mW2OK9ugD/B6MGJwhfGbK8cXdbPgKf1o4x+9TNmJdmYdE8jHnIJx9zhQOFCRAjyIrZsVtA0A==" />
    

    <link rel="stylesheet" media="all" href="/assets/application-e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855.css" data-turbolinks-track="reload" />
    <script src="/assets/application-4850ef4d32dbc32d7b439b8e85c9a90c2bb78aea3cafa296f093261db9ff9749.js" data-turbolinks-track="reload"></script>
  </head>

  <body>
    <h1>Hello from Rails on SCF!</h1>
2019-01-25T13:48:52+00:00

<ul>
  <li>#1: Drink coffee</li>
  <li>#2: Go to work</li>
  <li>#3: Have some rest</li>
</ul>

  </body>
</html>

Another thing is that the example is not that good. For me it is not clear that information is stored in a db. Could we find a better?

**Comment by cjschroder** [comment]
closing for 57c6a9035403ad85eb38.

I'll create a new issue for a better example app.
