### ISSUE TITLE
[doc] 3.1.1  SUSE CaaS Platform 3 PodSecurityPolicy

### ISSUE THREAD

**Issue by cduch** [SUSE/doc-cap#312]
3.1.1  SUSE CaaS Platform 3 PodSecurityPolicy

https://www.suse.com/documentation/cloud-application-platform-1/singlehtml/book_cap_guides/book_cap_guides.html#sec.cap.caasp-3

The file cap-psp-rbac.yaml is missing some serviceaccounts which will result in a broken deployment.

add the following lines to the file:

```
- kind: ServiceAccount
  name: default-privileged
  namespace: scf
- kind: ServiceAccount
  name: node-reader
  namespace: scf
```

**Comment by cjschroder** [comment]
Closing for https://github.com/SUSE/doc-cap/pull/313, thank you @cduch
