### ISSUE TITLE
Add descriptions for Log Levels 

### ISSUE THREAD

**Issue by tgeek77** [SUSE/doc-cap#315]
17.2  Log Levels

https://www.suse.com/documentation/cloud-application-platform-1/singlehtml/book_cap_guides/book_cap_guides.html#sec.cap.log-levels

Rather than just an example of logs at each level, a succinct description of each log level would be best.

**Comment by btat** [comment]
Thanks @tgeek77! Can you take a look at #320 . I only added some generic descriptions as the information provided at each log level is determined by each component and this could differ from component to component.
