### ISSUE TITLE
Storage requirements / prerequisites - How much storage do I need?

### ISSUE THREAD

**Issue by troytop** [SUSE/doc-cap#316]
As an operator
I want to know how many GB of persistent storage is required by CAP
So that I can plan and budget for my CAP deployment.

We need to find out and document how much storage space a typical CAP deployment requires and provide guidelines on how much storage an admin can expect to need for operations at various scales. The first number is easier to find and the more urgent requirement. The "at scale" numbers will depend on cluster configuration and expected usage, so they could go in the sizing guide.

**Comment by cjschroder** [comment]
Closing as this is not ready for documentation. We need a reliable tested source document with all the steps in order.
