### ISSUE TITLE
Document that creation of privileged PSPs is handled by the product (1.3.1)

### ISSUE THREAD

**Issue by satadruroy** [SUSE/doc-cap#317]
Users do not have to manually create a privileged PSP as mentioned in the SUSE CaaSP PSP section - from 1.3.1, both privileged and non-privileged PSPs are automatically applied. However, we still need to retain the content in that section around custom PSPs, i.e.,  if users do supply a custom PSP they need to make sure SYS_RESOURCE capabilities are specified for appropriate roles.  

This content is applicable to all platforms, not just CaaSP. 

This should supercede #251

**Comment by cjschroder** [comment]
@satadruroy See the rocket chat history-- the psp.yaml file still has to be created and applied. Though I've been getting conflicting information on this since CaaSP started supporting RBACs.

**Comment by cjschroder** [comment]
The difference in 1.3.1 is the `psp:` entries in scf-config-values.yaml are unnecessary.

**Comment by mook-as** [comment]
Hmm, that should not be necessary; in 1.3.1, if you don't specify the `psp:` entries, it should use the built-in ones.  After all, if you supply them (but do not name them), the helm chart has no way to know which one you wanted to use?

**Comment by cjschroder** [comment]
marking as blocked until authoritative info arrives.

**Comment by troytop** [comment]
The info from @mook-as is correct.
