### ISSUE TITLE
Stratos documentation needs to be consistent and up-to-date across various repos and public site

### ISSUE THREAD

**Issue by satadruroy** [SUSE/doc-cap#318]
There are numerous differences between the version on the public site and the Stratos repo documentation (https://github.com/cloudfoundry-incubator/stratos/tree/v2-master/deploy/kubernetes), e.g., in the public site requirement for storage classes is not mentioned, there is no reference to auto-enabling load balancers etc.

Need to sync up the content.

**Comment by cjschroder** [comment]
Pecking away at this:

https://github.com/SUSE/doc-cap/commit/286aefddc29ac3a10e03ff3021cf8210ffe8f05b
https://github.com/SUSE/doc-cap/pull/378

**Comment by cjschroder** [comment]
Good enough for now, with environment-specific instructions for CaaSP, AKS, and EKS. Load balancers with CaaSP is gnarly and will be handled separately.
