### ISSUE TITLE
Content for each platform should be self-sufficient

### ISSUE THREAD

**Issue by satadruroy** [SUSE/doc-cap#319]
The current feeling is readers still have to hop around from section to section from different platforms to complete a deployment (e.g., from within the AKS chapter, I've to go back to a section in CaaSP to do the actual helm chart deployment). It'd be nice to have content for each platform that is complete on its own but not sure if this can be done without any content duplication.

**Comment by cjschroder** [comment]
Agreed. There might be a way to include sections using XML. I'll look at this while I'm looking at doing a bit of reorg & cleanup

**Comment by cjschroder** [comment]
Ha. There is. *computer voice* **Working**...

**Comment by cjschroder** [comment]
The basic structure for repeating content is in place. https://github.com/SUSE/doc-cap/pull/341, https://github.com/SUSE/doc-cap/pull/339, https://github.com/SUSE/doc-cap/pull/338
