### ISSUE TITLE
[doc] 7.5  Enable Swap Accounting

### ISSUE THREAD

**Issue by it-slav** [SUSE/doc-cap#325]
7.5  Enable Swap Accounting

https://www.suse.com/documentation/cloud-application-platform-1/singlehtml/book_cap_guides/book_cap_guides.html#sec.cap.swap-accounting

I just reported #324 and as a result:
export VMNODES=$(az vm list --resource-group $MCRGNAME -o json | jq -r '.[] | select (.tags.poolName | contains("'$NODEPOOLNAME'")) | .name') does not work

For me export VMNODES=$(az vm list --resource-group $MCRGNAME -o json | jq -r '.[] | select (.tags.poolName) | .name') worked

**Comment by btat** [comment]
This is dependent on #324

**Comment by btat** [comment]
Closing this as #324 is now resolved. The nodepool name doesn't not accept uppercase letters. This command will work when a valid nodepool name is used.
