### ISSUE TITLE
[doc] 4.3.2  Connecting Stratos Metrics

### ISSUE THREAD

**Issue by it-slav** [SUSE/doc-cap#326]
4.3.2  Connecting Stratos Metrics

https://www.suse.com/documentation/cloud-application-platform-1/singlehtml/book_cap_guides/book_cap_guides.html#sec.cap.stratos-metrics-connect

The gui ask for an url for the endpoint. What shall I enter there?

**Comment by btat** [comment]
@nwmac ^^

**Comment by btat** [comment]
Hi @it-slav,  you can find the endpoint to enter using `kubectl get service susecf-metrics-metrics-nginx --namespace=metrics`. It will be listed as the `EXTERNAL-IP`. This is currently mentioned at the end of the [Install Stratos Metrics with Helm](https://www.suse.com/documentation/cloud-application-platform-1/singlehtml/book_cap_guides/book_cap_guides.html#sec.cap.stratos-metrics-install) section. I've moved this information to the "Connecting Stratos Metrics" section as part of https://github.com/SUSE/doc-cap/pull/363 to hopefully clear things up.
