### ISSUE TITLE
Typo in command for "Removing Service Broker Sidecar Deployments"

### ISSUE THREAD

**Issue by svollath** [SUSE/doc-cap#331]
Within that section there's the command for removing the driver-endpoint:

`tux > cf usb delete-driver-endpoint "http://cf-usb-sidecar-mysql.mysql-sidecar:8081"`

While it's missing a dash here, I wasn't able to delete an endpoint by specifying its URL - so according to 

```
> cf usb-delete-driver-endpoint --help
NAME:
   usb-delete-driver-endpoint - Delete a driver instance

USAGE:
   cf usb-delete-driver-endpoint NAME
```

we should change the commands to list them, and delete them by name. E.g.:

```
tux > cf usb-driver-endpoints
tux > cf usb-delete-driver-endpoint <endpoint-name>
```

... and don't forget the "-".

**Comment by btat** [comment]
Thanks @svollath! #332 has been made to fix this.
