### ISSUE TITLE
AKS specify Kubernetes version when creating instances

### ISSUE THREAD

**Issue by it-slav** [SUSE/doc-cap#333]
8.2  Create Resource Group and AKS Instance

https://susedoc.github.io/doc-cap/develop/cap-guides/html/cha.cap.depl-azure.html#sec.cap.create-aks-instance

When doing aks create vm
Please add --kubernetes-version and a version that has been tested. Right now 1.11.5 seems like a good choice.
That will make enable swap later work and make the nodes become Ready.

**Comment by btat** [comment]
@it-slav was the Kubernetes version used related to the issue with `--nodepool-name` you were having in https://github.com/SUSE/doc-cap/issues/324?

**Comment by it-slav** [comment]
I do not know and I do not want to break my installation again to figure out.
Have you tried yourself?

**Comment by cjschroder** [comment]
This isn't really a documentation issue until we have a definitive answer from engineering, you should post this on paas-devel@suse.de.

**Comment by troytop** [comment]
Please let's reopen this and mark it as blocked. It seems like a real issue, and even though Docs is not responsible for figuring it out, we need to have it open so we can reference it (and not ultimately fix the docs IF that's necessary).

**Comment by satadruroy** [comment]
The k8s version is now being passed in to the `az aks create` command in the latest documentation so this can be closed. Also see #324 for the latest updates.

https://susedoc.github.io/doc-cap/develop/cap-guides/html/cha.cap.depl-azure.html#sec.cap.create-aks-instance
