### ISSUE TITLE
Document that Stratos to not use port 80 by default when using load balancers.

### ISSUE THREAD

**Issue by gaktive** [SUSE/doc-cap#351]
Reported internally some time ago during a CaaSP upgrade, afterwards CAP stopped responding.

Since there's a bit of a race condition at play, it looks like Stratos came up first and grabbed port 80. The operator changed the NodePort of susecf-console-ui-ext to be on port 8080 instead of port 80 and everything worked again. 

Suggestion: have the Stratos installation documentation updated to prevent this by setting the http traffic to a port different than port 80, as it already sets the https traffic to port 8443.

**Comment by cjschroder** [comment]
That looks OK as a short-term fix. Wouldn't it be better to have a real fix, like Stratos always grabs port 8080? Then it's consistent in all environments, and we don't have to make customers wade through exceptions.

**Comment by gaktive** [comment]
Let's file a request with the Stratos team to see if they can grab another port first. We can document the current behaviour in the short term until that's addressed.

**Comment by btat** [comment]
Filed https://github.com/SUSE/stratos/issues/144
