### ISSUE TITLE
[doc] 3.3  DNS management

### ISSUE THREAD

**Issue by otuominen** [SUSE/doc-cap#356]
3.3  DNS management

https://www.suse.com/documentation/cloud-application-platform-1/singlehtml/book_cap_guides/book_cap_guides.html#id-1.3.4.3.5

What are the necessary domains and subdomains needed to be setup beforehand?

**Comment by btat** [comment]
Hi @otuominen, you can find more detailed information in the platform specific sections for [AKS](https://www.suse.com/documentation/cloud-application-platform-1/singlehtml/book_cap_guides/book_cap_guides.html#cha.cap.depl-azure) and [EKS](https://www.suse.com/documentation/cloud-application-platform-1/singlehtml/book_cap_guides/book_cap_guides.html#cha.cap.eks). 

In summary, you'll need mappings for:
- uaa.DOMAIN
- *.uaa.DOMAIN
- DOMAIN
- *.DOMAIN
- tcp.DOMAIN
- ssh.DOMAIN

Where DOMAIN is what you've set in your `scf-config-values.yaml`. The IPs/hostnames needed for the mappings will be available once `uaa` has been deployed and obtained using `kubectl get services`, e.g. `kubectl get services --namespace uaa | grep public`. Similarly, you would deploy `scf` and obtain the IPs/hostnames needed.
