### ISSUE TITLE
[doc] 5.3.2  Connecting Stratos Metrics

### ISSUE THREAD

**Issue by dsohk** [SUSE/doc-cap#361]
5.3.2  Connecting Stratos Metrics

https://www.suse.com/documentation/cloud-application-platform-1/singlehtml/book_cap_guides/book_cap_guides.html#sec.cap.stratos-metrics-connect

At this point, the stratos UI expects administrator to enter an end point for metrics type of connection. Where should we get this information?

**Comment by btat** [comment]
Hi @dsohk ,  you can find the endpoint to enter using `kubectl get service susecf-metrics-metrics-nginx --namespace=metrics`. It will be listed as the `EXTERNAL-IP`. Prepend `https://` to the value found and enter that into the field. 

The command to find the endpoint is currently mentioned at the end of the [Install Stratos Metrics with Helm](https://www.suse.com/documentation/cloud-application-platform-1/singlehtml/book_cap_guides/book_cap_guides.html#sec.cap.stratos-metrics-install) section. I've moved this information to the "Connecting Stratos Metrics" section as part of https://github.com/SUSE/doc-cap/pull/363 to hopefully clear things up.

**Comment by dsohk** [comment]
Thanks @btat 

I deployed it on AWS EKS cluster. The command "kubectl get service susecf-metrics-metrics-nginx --namespace=metrics" does not give me the EXTERNAL-IP because it's a nodeport typed service. 

In the section [Connecting Stratos Metrics](https://www.suse.com/documentation/cloud-application-platform-1/singlehtml/book_cap_guides/book_cap_guides.html#sec.cap.stratos-metrics-connect), it missed the step "Enter endpoint" after "Step 2 Enter a memorable name for your environment in the name field." I'd suggest you refer to where the reader should find the endpoint at there.

In the same section, it says

1. Click on Connect in the dropdown menu
2. Enter the username for your Stratos Metrics instance
3. Enter the password for your Stratos Metrics instance
4. Click Connect

What should the username and password field be? Is it the credential defined in stratos-metrics-values.yaml as described in section [Install Stratos Metrics with Helm](https://www.suse.com/documentation/cloud-application-platform-1/singlehtml/book_cap_guides/book_cap_guides.html#sec.cap.stratos-metrics-install)? The documentation on this part need to be elaborated.

Thanks,
Derek

**Comment by btat** [comment]
Hi @dsohk 

> I deployed it on AWS EKS cluster. The command "kubectl get service susecf-metrics-metrics-nginx --namespace=metrics" does not give me the EXTERNAL-IP because it's a nodeport typed service.

I'll need to confirm what's expected in your case then, because we recommend using a load balancer for EKS deployments. In the example from the [Metrics docs](https://github.com/SUSE/stratos-metrics#deploying-metrics-in-eks) (which uses a LB), the command should produce a hostname to use.
 
> In the section [Connecting Stratos Metrics](https://www.suse.com/documentation/cloud-application-platform-1/singlehtml/book_cap_guides/book_cap_guides.html#sec.cap.stratos-metrics-connect), it missed the step "Enter endpoint" after "Step 2 Enter a memorable name for your environment in the name field." I'd suggest you refer to where the reader should find the endpoint at there.

This has been taken care of by PR #363 

> In the same section, it says
> 
>     1. Click on Connect in the dropdown menu
> 
>     2. Enter the username for your Stratos Metrics instance
> 
>     3. Enter the password for your Stratos Metrics instance
> 
>     4. Click Connect
> 
> 
> What should the username and password field be? Is it the credential defined in stratos-metrics-values.yaml as described in section [Install Stratos Metrics with Helm](https://www.suse.com/documentation/cloud-application-platform-1/singlehtml/book_cap_guides/book_cap_guides.html#sec.cap.stratos-metrics-install)? The documentation on this part need to be elaborated.

I've added PR https://github.com/SUSE/doc-cap/pull/364 to address this
