### ISSUE TITLE
[doc] 8.6  Deploy SUSE Cloud Application Platform with a Load Balancer

### ISSUE THREAD

**Issue by it-slav** [SUSE/doc-cap#369]
8.6  Deploy SUSE Cloud Application Platform with a Load Balancer

https://www.suse.com/documentation/cloud-application-platform-1/singlehtml/book_cap_guides/book_cap_guides.html#sec.cap.cap-on-azure

The azure doc workflow miss essential parts. Like 
helm repo add suse https://kubernetes-charts.suse.com/
and storage

**Comment by btat** [comment]
Hi @it-slav these have been added in https://github.com/SUSE/doc-cap/pull/370 now
