### ISSUE TITLE
add some general load balancer guidance for CaaSP

### ISSUE THREAD

**Issue by cjschroder** [SUSE/doc-cap#377]
It's not possible to provide howtos for all load balancers, though we can document some specific environments, such as AKS and EKS. However we can provide some general guidance, and maybe find some examples to replace the current examples that map the CAP domain to a worker node.

**Comment by cjschroder** [comment]
This applies to CAP on CaaSP.

**Comment by KucharczykL** [comment]
Probably not on us. Closing for now.
