### ISSUE TITLE
Review EKS chapter for accuracy

### ISSUE THREAD

**Issue by cjschroder** [SUSE/doc-cap#386]

**Comment by btat** [comment]
The `Getting Started with Amazon EKS`[1] link now provides 2 guides. A new `Getting started with eksctl`[2] guide is now available and described as `This is the fastest and simplest way to get started with Amazon EKS`. Need to test this guide and see whether it is easier. Cluster creation is completed using a cli and would be more consistent with the steps listed for other public cloud platforms.

[1] https://docs.aws.amazon.com/eks/latest/userguide/getting-started.html
[2] https://docs.aws.amazon.com/eks/latest/userguide/getting-started-eksctl.html

**Comment by btat** [comment]
Closing this as our docs should be updated to use the `eksctl`-based instructions
