### ISSUE TITLE
Remove labels from all URLs

### ISSUE THREAD

**Issue by cjschroder** [SUSE/doc-cap#388]
URLs with labels do not render nicely in PDFs or print HTML, so all labels need to be removed from the whole CAP guide. For example, change `<link xlink:href="https://docs.aws.amazon.com/eks/latest/userguide/getting-started.html">Getting Started with Amazon EKS</link>` to `<link xlink:href="https://docs.aws.amazon.com/eks/latest/userguide/getting-started.html"/>`

**Comment by btat** [comment]
Note, the sentence the link occurs in may require adjustment to make sense once the label is removed from the link.

In the example above, the link label is used as part of a sentence: `See Getting Started with Amazon EKS for instructions on creating a &kube; cluster for your &productname; deployment.` Directly removing the label without change to the original sentence still makes sense in this context, but may not for others.

**Comment by cjschroder** [comment]
Yes, that is a good point. This is going to be fair bit of work, because without URL labels you need to write descriptive sentences. Here are some examples:

https://www.suse.com/documentation/sles-15/singlehtml/book_sle_admin/book_sle_admin.html#sec.zypper.more
"For a complete and detailed command reference, cheat sheets with the most important commands, and information on how to use Zypper in scripts and applications, refer to http://en.opensuse.org/SDB:Zypper_usage"

https://www.suse.com/documentation/sles-15/singlehtml/book_sle_admin/book_sle_admin.html#sec.net.rsync.summary
"For More Information
CSync
Bidirectional file synchronizer, see https://www.csync.org/. 
RSnapshot
Creates incremental backups, see http://rsnapshot.org. "

https://www.suse.com/documentation/sles-15/singlehtml/book_sle_admin/book_sle_admin.html#fig.grub2.yast.kernel.parameters
"For a list of all possible parameters, see http://en.opensuse.org/Linuxrc." 

The reason for not using URL labels is they do not render correctly in PDF output. We must instead write descriptive sentences so readers know what the URL is for, and for seach engine optimization.

**Comment by gaktive** [comment]
Billy to merge what work had been done here and then put this in the backlog for now until it's time to look at this again.

**Comment by btat** [comment]
Work from #462 merged. There are still additional URL labels to remove at a later time.
