### ISSUE TITLE
Update terminology and formatting according to style guide

### ISSUE THREAD

**Issue by cjschroder** [SUSE/doc-cap#389]
Terminology: https://doc.opensuse.org/documentation/styleguide/app.terminology.html#sec.terminology

Instances of the following terms need to be changed:
- `hostname` to `host name`
- `command-line` to `command line`
- `backend` to `back-end`
- `email` to `e-mail`
- `once` to `after`, adverb; only use `once` in the meaning of “one time only”
- `doesn't` to `does not`

Other:
- add space to units of measure, e.g. `8GB` to `8 GB`
- casing of titles/headings

**Comment by btat** [comment]
Updated to be more general and changed initial description to be a list of terms spotted requiring change.

**Comment by cmarin21** [comment]
Hi,

Could you please clarify me what shall I look for in "casing of titles/headings"? It's not clear to me.
Thanks.

**Comment by cjschroder** [comment]
> Hi,
> 
> Could you please clarify me what shall I look for in "casing of titles/headings"? It's not clear to me.
> Thanks.

Hi Claudia, there are many title elements, such as section, chapter, book, warning, tip, and so on. The Style Guide says to use title case for all titles, and I'm pretty sure you will find some that need to be corrected. http://docserv.nue.suse.com/documents/Style_Guide/docu_styleguide/single-html/#sec.capitalization

**Comment by btat** [comment]
Resolved by #440
