### ISSUE TITLE
AKS vCPU prerequisite and quota

### ISSUE THREAD

**Issue by tgeek77** [SUSE/doc-cap#415]
8.1  Prerequisites

https://www.suse.com/documentation/cloud-application-platform-1/singlehtml/book_cap_guides/book_cap_guides.html#sec.cap.prereqs-azure

Add Note:

24 vCPUs will be required for a minimal installation. If your account only has the default 10 vCPUs available, you can request a quote increase by going to the following page. https://docs.microsoft.com/en-us/azure/azure-supportability/resource-manager-core-quotas-request

**Comment by btat** [comment]
Thanks @tgeek77! Can you take a look at https://github.com/SUSE/doc-cap/pull/416 to see if it looks ok to you.
