### ISSUE TITLE
[doc] 8.6  DNS Configuration

### ISSUE THREAD

**Issue by tgeek77** [SUSE/doc-cap#418]
8.6  DNS Configuration

https://www.suse.com/documentation/cloud-application-platform-1/singlehtml/book_cap_guides/book_cap_guides.html#sec.cap.aks-dns

Note: 

A public IP directed at a worker node or to an Azure load balancer is required before setting up DNS. For more information, see: https://docs.microsoft.com/en-us/azure/aks/static-ip and https://docs.microsoft.com/en-us/azure/aks/internal-lb

**Comment by btat** [comment]
@tgeek77 When using the current documented steps, a load balancer is automatically created for external services and will have a public IP assigned. Are you running into issues with the current steps leading to your suggestion?

**Comment by tgeek77** [comment]
Hi Billy,

"When using the current documented steps, a load balancer is automatically created for external services and will have a public IP assigned."

I'm sorry but it isn't. To test this, I deleted all of my assets and started again fresh slowly step by step.

In section 8.2 you have have all of the steps to set up the resource group, AKS instance, and their VMs.

This command takes care of settings up AKS but it does not set up a load balancer:

az aks create --resource-group $RGNAME --name $AKSNAME \
 --node-count $NODECOUNT --admin-username $ADMINUSERNAME \
 --ssh-key-value $SSHKEYVALUE --node-vm-size $NODEVMSIZE \
 --node-osdisk-size=60 --nodepool-name $NODEPOOLNAME \
 --kubernetes-version 1.11.8

section 8.8 says "Deploying SUSE Cloud Application Platform with a Load Balancer
This section describes how to deploy SUSE Cloud Application Platform with a basic AKS load balancer, how to set up the required storage class, and how to configure your DNS records." but the steps on how to set up the load balancer and IP are missing. It is assumed that you've already done this on your own.

I'm trying to work through this on my own and I can share my notes, but for right now the steps are incomplete and anyone using the official docs will need to research this on their own also or else the steps will not work.

You can reach me on Rocketchat (Jason Evans) or we can set up a meeting to talk about it. I've talked to Carla a little about this already also.

**Comment by btat** [comment]
Hi Jason,

The load balancer (and its IP) for the UAA service are set up once you deploy UAA and likewise the for SCF services when SCF is deployed. This is done automatically through the inclusion of `services.loadbalanced=true` in the deployment config. The load balancer and IP do not need to be manually created. Note that this applies to other public cloud platforms too.

In previous revisions we had a longer and more explicit excerpt about `services.loadbalanced=true` and the magic it does, but was removed afterwards. In the current iteration, the below sections briefly mention the load balancer/IP automatic creation. Admittedly these are easy to miss and could use further explanation about the automagic `services.loadbalanced`.

I will be away until May 15. We could set something up to discuss this when I return.

```
8.8.2 Deployment Configuration

It is not necessary to create any DNS records before deploying uaa. Instead, after uaa is running you will find the load balancer IP address that was automatically created during deployment, and then create the necessary records.

8.8.3 Deploy uaa

Once the deployment completes, a Kubernetes service for uaa will be exposed on an Azure load balancer that is automatically set up by AKS

8.8.4 Deploy scf

Once the deployment completes, a number of public services will be setup using a load balancer that has been configured with corresponding load balancing rules and probes as well as having the correct ports opened in Network Security Group.
```

**Comment by btat** [comment]
Checked with Jason and this item is fine for now.
