### ISSUE TITLE
[CAP-317] sle12 deprecation notice

### ISSUE THREAD

**Issue by jimmykarily** [SUSE/doc-cap#423]
We should inform CAP users that in some future release (2.0?), sle12 stack will no longer be available. They should switch to the (already available) sle15 stack until that happens. The process to do that should be the same as upstream switch from cflinuxfs2 -> cflinuxfs3. More information here:

- https://github.com/cloudfoundry/cf-deployment/releases/tag/v8.0.0
- https://docs.google.com/document/d/12YMRhw1KoTQuNGCxcWpSn8TxQJ4s-5fpc1QQ7egKBB4/edit#heading=h.bq1gn3dqdg4a

We should test run the above process with sle12/sle15 stacks and make sure it is working as expected. Then we should document it and let people know (in the public docs) when sle12 will be removed.

**Comment by btat** [comment]
@jimmykarily can you link the corresponding card for the testing portion so that I can see when the process is verified for sle12/sle15 and proceed with the docs portion. Thanks.
