### ISSUE TITLE
Provide security considerations for the tiller component

### ISSUE THREAD

**Issue by jandubois** [SUSE/doc-cap#438]
Currently we recommend to create a tiller service account with a `cluster-admin` binding. There is no warning whatsoever that this provides *every* user on the cluster with a mechanism to create any kind of object in any namespace with any kind of permission (like `sudo` without requiring a password).

This means that *every* user has access to *every* secret stored anywhere in the cluster.

I would prefer that we don't document the service account at all, and just say "Install tiller (the helm server component) on your cluster, appropriately secured according to your requirements" and point them at https://github.com/helm/helm/blob/master/docs/securing_installation.md

If we really have to provide the "cluster-admin" example, we need to put a huge disclaimer on it (copying from the helm docs):

> This default installation applies **no security configurations**, however. It's completely appropriate to use this type of installation when you are working against a cluster with no or very few security concerns, such as local development with Minikube or with a cluster that is well-secured in a private network with no data-sharing or no other users or teams.

But the current docs leave the impression that the example setup is appropriate for production usage, which it clearly isn't.

**Comment by troytop** [comment]
Relevant Helm docs: https://helm.sh/docs/using_helm/#securing-your-helm-installation
