### ISSUE TITLE
Deploy Stratos on Microsoft AKS: incorrect values.yaml filename

### ISSUE THREAD

**Issue by alexrenna** [SUSE/doc-cap#444]
6.3  Deploy Stratos on Microsoft AKS

https://www.suse.com/documentation/cloud-application-platform-1/singlehtml/book_cap_guides/book_cap_guides.html#sec.cap.stratos-aks

**Comment by alexrenna** [comment]
For AKS should be "--values scf-azure-values.yaml"

**Comment by btat** [comment]
Good catch, thanks @alexrenna . Fixed in https://github.com/SUSE/doc-cap/commit/3ced883e0fe9bd2c7ec7fcee7b64c78ed3ed7cb4 now
