### ISSUE TITLE
AKS can't pull AKS service broker image via doc instructions

### ISSUE THREAD

**Issue by HartS** [SUSE/doc-cap#448]
A [kubernetes issue](https://github.com/kubernetes/kubernetes/pull/66429) and/or [azure service broker issue](https://github.com/Azure/open-service-broker-azure/issues/700) is causing `open-service-broker-azure` installation to fail due to inability to pull the `osbapublicacr.azurecr.io/microsoft/azure-service-broker:v1.6.0` image. Upgrading the AKS kubernetes version to 1.11.9 will fix this issue, but does require some additional workarounds and considerations which should also be documented

**Comment by btat** [comment]
See #449 for additional workarounds and considerations
