### ISSUE TITLE
Update information about scf-config-values.yaml in the CaaSP Deployment Guide

### ISSUE THREAD

**Issue by cmarin21** [SUSE/doc-cap#450]
Going through the deployment guide for the first time, I found this section explained too high level: https://www.suse.com/documentation/cloud-application-platform-1/book_cap_guides/data/sec_cap_configure-prod.html

The example scf-config-values.yaml file is for a simple deployment without an ingress controller or external load balancer. Instead, assign one worker node an external IP address, and map this to the domain name to provide external access to the cluster. The external_ips parameter needs this address to provide access to the Stratos Web interface and other public servers, and it needs the internal IP addresses of the worker nodes to provide access to internal services. 

I would suggest to create a better explanation, like which IP should I take from where (for example, Open Stack) and update which section in the scf-config-values.yaml:
- something like, take the master node's external IP and paste it into the DOMAIN. Add the xip.io after the IP. It should look something similar to this, <your_IP>.xip.io
- update the uaa with the same information following the structure: uaa.<your_IP>.xip.io
- update the external_ips field with the Internal IP of the master node.

**Comment by btat** [comment]
> something like, take the master node's external IP and paste it into the DOMAIN. Add the xip.io after the IP. It should look something similar to this, <your_IP>.xip.io
>
>update the uaa with the same information following the structure: uaa.<your_IP>.xip.io

Keep in mind that `example.com` is the example domain we use throughout the docs. We should not be using wildcard DNS services like xip or nip if possible.

**Comment by cmarin21** [comment]
Billy - thanks for the hints.
So, I was not sure which values I should have written in the DOMAIN. The team explained me I should put .xip.io at the end of it. 
Does your comment mean that I should avoid using xip in the documentation?

**Comment by btat** [comment]
> Billy - thanks for the hints.
> So, I was not sure which values I should have written in the DOMAIN. The team explained me I should put .xip.io at the end of it.
> Does your comment mean that I should avoid using xip in the documentation?

Replied on Rocketchat

**Comment by btat** [comment]
Also note 6.1 Deploy Stratos on SUSE® CaaS Platform (https://www.suse.com/documentation/cloud-application-platform-1/singlehtml/book_cap_guides/book_cap_guides.html#sec.cap.stratos-prod) mentions using worker node. Ensure that section is consistent with any updates that may be made here.
