### ISSUE TITLE
Clarify Expected Pod Status of Successful UAA Deployment

### ISSUE THREAD

**Issue by cmarin21** [SUSE/doc-cap#451]
Going through the deployment guide for the first time, I found this section explained too high level: https://www.suse.com/documentation/cloud-application-platform-1/book_cap_guides/data/sec_cap_install-uaa-prod.html

Describe in more details than there are currently there, when a deplyment is considered as being successful. What needs to happen?!
- mysql-0, uaa pods should have the READY column 1/1, and the STATUS column Running
- secret-generation-1-s7lmx should have the READY column as 0/1, and the STATUS column should be Completed

**Comment by cmarin21** [comment]
The output should be something like that:
NAME                                         READY     STATUS      RESTARTS   AGE
mysql-0                                           1/1          Running             0          10m
secret-generation-1-s7lmx              0/1       Completed            0          13m
uaa-0                                              1/1          Running             0          13m

**Comment by btat** [comment]
Note the update to the "successful install" output should be applied for all platforms. The content can be the same for each platform in which case an entity can be used.

**Comment by btat** [comment]
```
NAME                        READY     STATUS      RESTARTS   AGE
mysql-0                     1/1       Running     0          1d
secret-generation-3-lwc7k   0/1       Completed   0          1d
uaa-0                       1/1       Running     0          1d
```
