### ISSUE TITLE
Clarify Expected Pod Status of Successful Stratos Deployment

### ISSUE THREAD

**Issue by cmarin21** [SUSE/doc-cap#461]
Deploy Stratos on SUSE® CaaS Platform requires more information for the following sections:

1) These instructions assume you have followed the procedure in Section 5.0, Deploying SUSE Cloud Application Platform on SUSE CaaS Platform, have deployed uaa and scf successfully, and have created a default storage class. 

To check you have created a default storage class (created during CaaSP deployment on ECP), run this command:
kubectl get storageclass

As results you should get something similar to this:
NAME                      PROVISIONER   AGE
persistent (default)        nfs                   11d

2) When all statuses show Ready, press Ctrl+C to exit. Query with Helm to view your release information.

I would add more information that your Stratos instillation is successful when the "statos" pods show Running, while "volume-migration" pod shows Completed:

NAME                                          READY     STATUS      RESTARTS   AGE
stratos-0                                          3/3          Running                  1          20m
stratos-db-c94c96d75-jj2mg           1/1          Running                  0          20m
volume-migration-1-qqvlk                0/1       Completed                0          20m

**Comment by btat** [comment]
> Deploy Stratos on SUSE® CaaS Platform requires more information for the following sections:
> 
> 1. These instructions assume you have followed the procedure in Section 5.0, Deploying SUSE Cloud Application Platform on SUSE CaaS Platform, have deployed uaa and scf successfully, and have created a default storage class.
> 
> To check you have created a default storage class (created during CaaSP deployment on ECP), run this command:
> kubectl get storageclass
> 
> As results you should get something similar to this:
> NAME PROVISIONER AGE
> persistent (default) nfs 11d

Checking for a default storage class is done as part of https://www.suse.com/documentation/cloud-application-platform-1/singlehtml/book_cap_guides/book_cap_guides.html#sec.cap.storageclass-prod, does it really need to be done again?

**Comment by cmarin21** [comment]
I wasn't sure how to check that I have created a  default storage class...
It was listed as a prerequisite so perhaps I did it somewhere in the past, but just getting at this point made it unclear. Of course I remember I did the uaa, scf deployment (because they were the steps right before deploying Stratos) but I did not remember about the storage class. So I would have found it useful to get some hints how to check that.
We can leave then the documentation as it is then...

**Comment by btat** [comment]
No worries, the existing documentation and CAP as a product take some time to become familiar with. In this situation it's better to link back to Ch 5 for the user to reference in case they need a refresher for any of the steps covered there.

**Comment by btat** [comment]
Note the update to the "successful install" output should be applied for the other platforms as well. The content can be the same for each platform in which case an entity can be used.

**Comment by cmarin21** [comment]
> Note the update to the "successful install" output should be applied for the other platforms as well. The content can be the same for each platform in which case an entity can be used.

Billy, I do not understand this note, could you please rephrase it for me?
Do you mean that the message we show to users when they have successfully deployed CAP (on whatever platform, Azure, Google, etc) it should be the same regardless of the platform they used?
What do you mean by "an entity can be used" - you mean in the docbookxml I shall use an "entity" as an element?
Thanks.

**Comment by btat** [comment]
> I would add more information that your Stratos instillation is successful when the "statos" pods show Running, while "volume-migration" pod shows Completed:
> 
> NAME READY STATUS RESTARTS AGE
> stratos-0 3/3 Running 1 20m
> stratos-db-c94c96d75-jj2mg 1/1 Running 0 20m
> volume-migration-1-qqvlk 0/1 Completed 0 20m

In the issue's description you suggested the adding the above to help make it more clear to users when a Stratos installation is complete/successful. The issue's title only mentions CaaSP, but the suggested change is applicable to all platforms.

When adding the suggested change to each platform, the content will be the same. Rather than copy and pasting, which is error prone/harder to maintain, Carla and I use entities (e.g. &some-entity;) for repeated content.

So instead of

```
<!-- Chapter 1 -->
<para>
 Something goes here.
 Another sentence is here.
 More sentences.
</para>

<!-- Chapter 2 -->
<!-- below is copy and pasted -->
<para>
 Something goes here.
 Another sentence is here.
 More sentences.
</para>
```

We define an entity inside `xml/repeated-content-decl.ent` for any repeated content. This could be a paragraph, list, table, etc. If there's an update to the content, then we only need to update 1 instance rather than multiple instances scattered about in many files.

Then use the entity and the output will be the same

```
<!-- Chapter 1 -->
&para-with-sentences;

<!-- Chapter 2 -->
<!-- below is copy and pasted -->
&para-with-sentences;
```

**Comment by cmarin21** [comment]
Billy,

This is much more clear to me now. The issue talks about CaaSP because this is where it happened for me, and I wanted to be very specific when raising an issue so that is clear when-where-how it all happened. It good to know that we can use entities so the content can be replaced in a safe way across many platforms.

**Comment by btat** [comment]
> The issue talks about CaaSP because this is where it happened for me, and I wanted to be very specific when raising an issue so that is clear when-where-how it all happened.

That's the correct approach. For cases where we get more info about the issue/story afterwards (like this one for example), we can update title and/or original description to reflect the new info.

Also note the entity/repeated output stuff applies for #451 and #459 too.

**Comment by cmarin21** [comment]
Ok, thanks for the info.

**Comment by btat** [comment]
```
NAME                          READY     STATUS      RESTARTS   AGE
stratos-0                     3/3       Running     0          2m
stratos-db-78cf5d7b67-zbd9l   1/1       Running     0          2m
volume-migration-1-qgnjj      0/1       Completed   0          2m
```
