### ISSUE TITLE
 difference between ROOTFS_TRUSTED_CERTS and TRUSTED_CERTS in the role-manifest

### ISSUE THREAD

**Issue by prabalsharma** [SUSE/doc-cap#465]
https://trello.com/c/jJmmr220/1069-3-investigate-the-difference-between-rootfstrustedcerts-and-trustedcerts-in-the-role-manifest

**Comment by KucharczykL** [comment]
What is the best place to document this? I only found one reference to these in the section https://documentation.suse.com/suse-cap/1.5.1/single-html/cap-guides/#app-scf-values-yaml.

**Comment by btat** [comment]
Maybe as a section in https://github.com/SUSE/doc-cap/blob/develop/xml/cap_admin_certificates.xml since these values are about certs
