### ISSUE TITLE
[doc] 25.1  Creating an Offline Buildpack

### ISSUE THREAD

**Issue by viccuad** [SUSE/doc-cap#468]
25.1  Creating an Offline Buildpack

http://docserv.nue.suse.com/documents/CAP_1/cap-guides/single-html/#sec.cap.create-offline-buildpack

The line ` Build the latest released SUSE Ruby buildpack for the SUSE Linux Enterprise 12 stack` should say SLE 15.

**Comment by btat** [comment]
Thanks! Fixed in https://github.com/SUSE/doc-cap/commit/7f8330a78debdce055d46712e933f4eb64573088
