### ISSUE TITLE
Document changes to availability zones in CAP 1.4.1+

### ISSUE THREAD

**Issue by jandubois** [SUSE/doc-cap#485]
In CAP 1.4.1 the default for `AZ_LABEL_NAME` will be `failure-domain.beta.kubernetes.io/zone`, which is the predefined kube label for the availability zone: https://github.com/SUSE/scf/pull/2506.

It is already pre-populated on kubernetes installations provided by most cloud providers, so AZ support will work out-of-the-box on those systems without further configuration.

If users want to implement availability zones for their on-premises installations, it is recommended that they label their nodes with the same label.

https://kubernetes.io/docs/reference/kubernetes-api/labels-annotations-taints/#failure-domainbetakubernetesiozone

Caution: For best performance all availability zones should have a similar number of nodes because app instances will be evenly distributed, so that each zone has about the same number of instances.

Note that due to a bug in CAP 1.4 and earlier, this label was not working for `AZ_LABEL_NAME`: https://github.com/SUSE/scf/pull/2505

**Comment by troytop** [comment]
If there's a way to disable this (if that is desired) we should document that too.

**Comment by jandubois** [comment]
> If there's a way to disable this

You can disable it by setting `AZ_LABEL_NAME` to the empty string (or any name that isn't actually a label on your nodes). That way all nodes will be in the same "unnamed" zone.
