### ISSUE TITLE
[doc] 21.5  Deploying the MySQL Chart

### ISSUE THREAD

**Issue by PriyankaProgrammer** [SUSE/doc-cap#512]
21.5  Deploying the MySQL Chart

https://www.suse.com/documentation/cloud-application-platform-1/singlehtml/book_cap_guides/book_cap_guides.html#sec.cap.configure-mysql

I m new to CAP platform, Please help me find following issue,
I am getting following error inside the mysql setup pod:
Registering MySQL sidecar with CC
ERROR:[POST /driver_endpoints][500] registerDriverEndpointInternalServerError  Could not connect to database
 Status: failed, Name: Database, Description: Server reply, Message: dial tcp: lookup mysql.example.com on 172.24.0.2:53: no such host

**Comment by btat** [comment]
Hi PriyankaProgrammer,

What platform is your CAP deployment using? Where is your MySQL instance hosted?

**Comment by btat** [comment]
Hi @PriyankaProgrammer, are you still experiencing issues with this? If so, could you please provide more information about the setup of your CAP deployment and MySQL instance?

**Comment by PriyankaProgrammer** [comment]
Hi, Sorry for the late reply. Now it's working fine. Thanks for your help.
