### ISSUE TITLE
CaaSP 4 CF diego-cell needs swapaccount=1

### ISSUE THREAD

**Issue by btat** [SUSE/doc-cap#515]
bsc#1142360 

This may be enabled/resolved on the CaaSP side, but will need to be documented in the meantime.

**Comment by gaktive** [comment]
CaaSP will not resolve on their side as this is only required for CAP running with Diego per their feedback. Therefore, we will need to document this for those CAP operators; Eirini users will not need that swap account setting.

**Comment by greygoo** [comment]
just a  short update, this will not be solved on the CaaSP side for RC1

**Comment by btat** [comment]
Swap accounting may not be required depending on the outcome of CAP-596 (applies to all platforms and not just CaaSP).
