### ISSUE TITLE
[doc] 24.3  Deploying SUSE Cloud Application Platform with Certificates

### ISSUE THREAD

**Issue by cduch** [SUSE/doc-cap#518]
24.3  Deploying SUSE Cloud Application Platform with Certificates

The doc describes how to get the CA_CERT but it's not used during helm install / upgrade.
This should be added.

https://www.suse.com/documentation/cloud-application-platform-1/singlehtml/book_cap_guides/book_cap_guides.html#sec.cap.cert-deploy

**Comment by btat** [comment]
Thanks @cduch! Fixed in https://github.com/SUSE/doc-cap/commit/1fa2783f104febffba8f262bf84ed35bfa01be47 now.
