### ISSUE TITLE
[doc] 10  Deploying SUSE Cloud Application Platform on Amazon Elastic Kubernetes Service (EKS)

### ISSUE THREAD

**Issue by tgeek77** [SUSE/doc-cap#542]
10  Deploying SUSE Cloud Application Platform on Amazon Elastic Kubernetes Service (EKS)

https://www.suse.com/documentation/cloud-application-platform-1/singlehtml/book_cap_guides/book_cap_guides.html#cha-cap-depl-eks

This section is missing an example of how to create a cluster in EKS similar to the steps given in: l#sec-cap-create-aks-instance

Create a cluster using the following command:

```
eksctl create cluster \
--name MyCluster \
--version 1.12 \
--node-type t2.large \
--node-volume-size 80 \
 --nodes 3 
```

This will take a few minutes and may stop responding for a brief time.

Enter the following commands to retrieve the kubeconfig information for your Kubernetes cluster and automatically create ~/.kube/config:

`eksctl utils write-kubeconfig --name MyCluster`

**Comment by zoopster** [comment]
FYI....`eksctl utils write-kubeconfig --name` will write the kubeconfig to env/kubeconfig.eks not to ~/.kube/config

**Comment by tgeek77** [comment]
With the latest version, it does write to ~/.kube/config.  This is from a lab that I wrote:
https://asciinema.org/a/o58xwScJVcfWj7x00oRNNjM0j

**Comment by zoopster** [comment]
By default you are correct. If there is a KUBECONFIG variable set...it will save it to the location defined by that variable...in my case env/kubeconfig.eks 
Thanks for making me look into that!

**Comment by btat** [comment]
Moving contents from here into #455
