### ISSUE TITLE
[doc] 10.5  Security Group rules

### ISSUE THREAD

**Issue by tgeek77** [SUSE/doc-cap#543]
10.5  Security Group rules

https://www.suse.com/documentation/cloud-application-platform-1/singlehtml/book_cap_guides/book_cap_guides.html#sec-cap-eks-secgroup-rules

Here are actual steps to perform this task:

Enter the following command to get a list of security_groups:
`aws ec2 describe-security-groups | grep SECURITYGROUPS
`
You will see at least four entries for this cluster. Review the one that says “_Communication between the control plane and worker nodegroups_”. The value beginning with sg- will be your security_group id. Example: sg-052314227da11fc7a

Enter the following commands to add the ingress rules to the security_group that you identified in the previous step:

```
aws ec2 authorize-security-group-ingress \
--group-id security_group --protocol tcp \
--port 80 --cidr 0.0.0.0/0

aws ec2 authorize-security-group-ingress \
--group-id security_group --protocol tcp \
--port 2793 --cidr 0.0.0.0/0

aws ec2 authorize-security-group-ingress \
--group-id security_group --protocol tcp \
--port 2222 --cidr 0.0.0.0/0

aws ec2 authorize-security-group-ingress \
--group-id security_group --protocol tcp \
--port 4443 --cidr 0.0.0.0/0

aws ec2 authorize-security-group-ingress \
--group-id security_group --protocol tcp \
--port 443 --cidr 0.0.0.0/0

aws ec2 authorize-security-group-ingress \
--group-id security_group --protocol tcp \
--port 20000-20009 --cidr 0.0.0.0/0
```

Review the ingress permissions for your security_group.
`aws ec2 describe-security-groups --group-id security_group`

**Comment by btat** [comment]
As per findings from @satadruroy, these are automatically set up when using `services.loadbalanced=true` and do not need to be done manually. Updated in #600.
