### ISSUE TITLE
Use reclaimPolicy retain for all storage classes

### ISSUE THREAD

**Issue by btat** [SUSE/doc-cap#554]
Some of the storage class manifest examples currently have

`reclaimPolicy: Delete`

These should be replaced by

`reclaimPolicy: Retain`

**Comment by troytop** [comment]
@satadruroy let us know if there are any side effects from this change.

**Comment by satadruroy** [comment]
The side effect is PVs will remain even after the PVCs are deleted so for demos and stuff people will have to remember to clean up. 

The other thing is even though with Retain reclaimPolicy the PV is retained once the api-group pods are restarted (and it appears they have to be as part of the recovery procedure from the problem @troytop ran into) they end up doing the complete CCDB migration anyway so effectively the data is overwritten - at least this is what I found from my tests. Will need to confirm with @mook-as

**Comment by mook-as** [comment]
Odd, if the (mysql) disk is still around, the migrations should be no-ops (because the db would have been marked as already migrated).  Perhaps it's using a new PV instead?

**Comment by btat** [comment]
After discussion with Satadru, this will be closed as we currently focus on using the default storage class already provided by the underlying IaaS and not custom storage classes.
