### ISSUE TITLE
[CAP-675] Embedded UAA and Ingress Compatability

### ISSUE THREAD

**Issue by btat** [SUSE/doc-cap#556]
With embedded UAA there's currently no mechanism to create an ingress via helm. Add instructions to update the ingress rules so that the ingress controller points to the UAA service created by the cf chart.

the ingress-tls cert will need to be valid for:

```
    - "*.uaa.{{ .Values.env.DOMAIN }}"
    - "uaa.{{ .Values.env.DOMAIN }}"
```

**Comment by jandubois** [comment]
I think there is no reasonable way to make this work with the CAP-1.5 charts. The release notes should just state that the ingress controller cannot be used together with the embedded UAA in this release.

**Comment by gaktive** [comment]
Release notes updated to reflect this:
> If you are using the `uaa` embedded in the `suse/cf` chart, note that automatic ingress creation via helm will not work at present.

**Comment by KucharczykL** [comment]
@btat Am I understanding correctly that there is still no way to do this as per https://github.com/SUSE/doc-cap/issues/556#issuecomment-529039989 or has something changed and we can actually address this?

**Comment by jandubois** [comment]
@KucharczykL I think this was implemented by https://github.com/SUSE/scf/commit/7671763 and the comment only says that it could not be made to work for the already released 1.5 chart. It should be working in 1.5.1+

QA has confirmed that it works: https://jira.suse.com/browse/CAP-675

**Comment by gaktive** [comment]
@btat Guess this is done based on #622 ? If so, go ahead and close this.

**Comment by btat** [comment]
@KucharczykL is currently reviewing the test steps/setup Sebi provided to ensure our current docs are in line with that. Will close once his review done.

**Comment by KucharczykL** [comment]
This is the related information: https://trello.com/c/l4lJjWGn/1625-embedded-uaa-with-ingress-controller
