### ISSUE TITLE
[doc] 13.2  Mirror Images to Registry

### ISSUE THREAD

**Issue by otuominen** [SUSE/doc-cap#566]
13.2  Mirror Images to Registry

https://susedoc.github.io/doc-cap/develop/cap-guides/single-html/#sec-cap-air-gap-registry

> IMAGES=$(cat ${CHARTDIR}/**/imagelist.txt)
No such file exists.

**Comment by btat** [comment]
@otuominen What version of CAP are you on? I believe imagelist.txt was included as part of the Helm charts starting in 1.4. (maybe @jandubois can confirm)

**Comment by jandubois** [comment]
Yes, this is a new feature, implemented for CAP-1.5. I did retrofit the latest released charts with `imagelist.txt` files, but that may have been CAP-1.4.1 and not CAP-1.4. It is not supported for older chart versions.

**Comment by otuominen** [comment]
1.5 rc 4

**Comment by btat** [comment]
As per Jan on `#cap-devel`

`The file may be missing in the RC builds; I think it is created as part of the publishing step to the suse registry`

Please reopen if there are additional issues regarding this.

**Comment by jandubois** [comment]
I think the `imagelist.txt` file is created as part of publishing the images to `registry.suse.com`, so it will not exist for internal builds that use the staging registry.

**Comment by btat** [comment]
The file seems to be there for me

```
$ helm fetch --devel --untar suse/cf && ls cf && cat cf/Chart.yaml 
Chart.yaml  imagelist.txt  templates  values.yaml
apiVersion: 2.18.0+cf9.5.0.0.ga2697c75
appVersion: 1.5.0
description: A Helm chart for SUSE Cloud Foundry
name: cf
version: 2.18.0-rc4

$ helm fetch --devel --untar suse/uaa && ls uaa && cat uaa/Chart.yaml 
Chart.yaml  imagelist.txt  templates  values.yaml
apiVersion: 2.18.0+cf9.5.0.0.ga2697c75
appVersion: 1.5.0
description: A Helm chart for SUSE UAA
name: uaa
version: 2.18.0-rc4
```

**Comment by btat** [comment]
@otuominen Do you still get `No such file exists` now that the charts no longer have the `-rc4` designation?

**Comment by otuominen** [comment]
@btat  Working now as expected. Case closed.
