### ISSUE TITLE
Certs chapter incorrect Helm value name

### ISSUE THREAD

**Issue by mauricebrinkmann** [SUSE/doc-cap#570]
25.2  Deployment Configuration

https://www.suse.com/documentation/cloud-application-platform-1/singlehtml/book-cap-guides/book-cap-guides.html#sec-cap-cert-config

ROUTER_SSL_KEY needs to be ROUTER_SSL_**CERT**_KEY

**Comment by btat** [comment]
Thanks @mauricebrinkmann! Fixed in https://github.com/SUSE/doc-cap/commit/ee589b53003d74c16359eb4ebd5ce62d86280c6a
