### ISSUE TITLE
Docs should include deployments on SUSE CaaS Platform 4 too

### ISSUE THREAD

**Issue by viccuad** [SUSE/doc-cap#575]
At:

5  Deploying SUSE Cloud Application Platform on SUSE CaaS Platform

http://docserv.nue.suse.com/documents/CAP_1/cap-guides/single-html/#cha-cap-depl-caasp

There should be examples about CaaSP4 deployments, not only CaaSP3.

**Comment by viccuad** [comment]
Let me take the low priority label out; customers getting CAP 1.4 ought to have deployment docs on CaaSP4.

**Comment by troytop** [comment]
Escalating as this is causing confusion with customers and partners. 

>    c) current release (1.5) documentation only cites deployment on SUSE
>    CaaS Platform 3 (whose general support ends next March), and no mention
>    on the current roadmap of when SUSE CaaS Platform 4 will be a supported
>    deployment option

Current docs should be for CaaS Platform 4.x only, which **is** supported.
