### ISSUE TITLE
Add "Updating Buildpacks" Section

### ISSUE THREAD

**Issue by dsohk** [SUSE/doc-cap#579]
28.1  Creating an Offline Buildpack

https://documentation.suse.com/suse-cap/1.5/html/cap-guides/cha-cap-offline-buildpacks.html#sec-cap-create-offline-buildpack

May I suggest we add another section about "Updating buildpack" and "check available buildpacks to update"? This is handy for deploying apps that may require a higher version of buildpack to work.

I found the following answer to the question is useful as part of the doc.

On Sep 24, 2019, at 3:14 PM, Derek So wrote:
Apparently, it requires go-1.10? Is there any way we can see the available buildpack versions from SUSE CAP? Can we update the buildpacks to a higher version without upgrading to SUSE CAP 1.5?

Hi Derek,

you can see the list of installed buildpack with the cf buildpacks command.

Available SUSE buildpacks are listed on the releases page on Github for each buildpack, e.g. Releases · SUSE/cf-go-buildpack

You can upgrade a buildpack with the cf update-buildpack command, e.g.

cf update-buildpack go_buildpack -p https://cf-buildpacks.suse.com/go-buildpack-v1.8.42.1-1.1-c93d1f83.zip

Cheers,
-Jan

**Comment by btat** [comment]
Thanks for the suggestion @dsohk, I'll add it in
