### ISSUE TITLE
[doc] 13.1  Enabling Eirini

### ISSUE THREAD

**Issue by zoopster** [SUSE/doc-cap#585]
13.1  Enabling Eirini
https://documentation.suse.com/suse-cap/1/html/cap-guides/cha-cap-depl-eirini.html#sec-cap-eirini-enable

This fails for me. It appears if you have Eirni enabled in your scf-config.values the chart will automatically create the namespace so the initial namespace creation is not necessary.

**Comment by btat** [comment]
Thanks @zoopster! Fixed in https://github.com/SUSE/doc-cap/commit/191f16b476c0695f1b353522a6b184205e0f09da
