### ISSUE TITLE
[doc] Figure&nbsp;1.4:  SUSE Cloud Application Platform Stack 

### ISSUE THREAD

**Issue by phakkarainen** [SUSE/doc-cap#590]
Figure&nbsp;1.4:  SUSE Cloud Application Platform Stack 

https://documentation.suse.com/suse-cap/1.5/single-html/cap-guides/#fig-cap-stack

Question:
Is there Operating System inside container or does it use services from kernel below?

**Comment by btat** [comment]
Containers in CAP are based on SLE.

As an example, you can verify the OS of the `api-group` container by taking a look at the `/etc/os-release` file.

```
$ kubectl exec -it -n scf api-group-0 -c api-group -- bash -c 'cat /etc/os-release'
NAME="SLES"
VERSION="12-SP4"
VERSION_ID="12.4"
PRETTY_NAME="SUSE Linux Enterprise Server 12 SP4"
ID="sles"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:12:sp4"
```
