### ISSUE TITLE
[doc] Figure&nbsp;1.1:  Minimal Example Production Deployment 

### ISSUE THREAD

**Issue by phakkarainen** [SUSE/doc-cap#591]
Figure&nbsp;1.1:  Minimal Example Production Deployment 

https://documentation.suse.com/suse-cap/1.5/single-html/cap-guides/#fig-cap-min-prod-arch

Comment:
This points exactly for CAASP 3. Should there be a note about the version or should this be updated for version 4.

**Comment by btat** [comment]
This will be updated as part of #575
