### ISSUE TITLE
[doc] 5.5  Configure the SUSE Cloud Application Platform Production Deployment

### ISSUE THREAD

**Issue by phakkarainen** [SUSE/doc-cap#593]
5.5  Configure the SUSE Cloud Application Platform Production Deployment

https://documentation.suse.com/suse-cap/1.5/single-html/cap-guides/#sec-cap-configure-prod

Question:
Aren't external_ips worker nodes?

**Comment by btat** [comment]
Worker nodes can be used for `external_ips`. Based on #450, master nodes can also be used. https://github.com/SUSE/doc-cap/commit/3399516c551361254587c30fb0040a9d69541515 has been created to revert #510 (which addressed the suggestions in #450) for consistency with other CAP resources regarding `external_ips` and avoid any confusion.
