### ISSUE TITLE
GARDEN_ROOTFS_DRIVER needs to be explicit in values.yaml for CaaSP

### ISSUE THREAD

**Issue by dwainsims** [SUSE/doc-cap#598]
5.5  Configure the SUSE Cloud Application Platform Production Deployment

https://documentation.suse.com/suse-cap/1.5/single-html/cap-guides/#sec-cap-configure-prod

If my further reading is correct, the GARDEN_ROOTFS_DRIVER variable should be set in the env: section of the file.  The CAP doc does not make it clear where you should stick this variable in the file.

We might want to consider sticking the variable in the example file (in the right spot), and just commenting it out.

**Comment by btat** [comment]
Thanks @dwainsims, fixed in https://github.com/SUSE/doc-cap/pull/601.
