### ISSUE TITLE
[doc] 5.5  Configure the SUSE Cloud Application Platform Production Deployment

### ISSUE THREAD

**Issue by dwainsims** [SUSE/doc-cap#605]
5.5  Configure the SUSE Cloud Application Platform Production Deployment

https://documentation.suse.com/suse-cap/1.5/single-html/cap-guides/#sec-cap-configure-prod

The GARDEN_ROOTFS_DRIVER stanza needs to go into the "env:" section of the scf-config-values.yaml file.  This should either be in the example or explicitly stated.

**Comment by btat** [comment]
Closing as duplicate of #598, which is fixed and soon to be published.
