### ISSUE TITLE
Updates for Helm 3 (and using Helm 2 in the meantime)

### ISSUE THREAD

**Issue by troytop** [SUSE/doc-cap#615]
For CAP 2.0, we will recommend using helm 3 for installation (pending validation), since helm 3.0.0 went GA today: https://github.com/helm/helm/releases/tag/v3.0.0

In the meantime, we should flag the documentation with a note that installation of CAP 1.x should be done with Helm 2.x

**Comment by btat** [comment]
Just a note, flag for `In the meantime, we should flag the documentation with a note that installation of CAP 1.x should be done with Helm 2.x` is already present.

**Comment by btat** [comment]
For CAP 2 docs, all Helm commands should be converted to Helm 3

**Comment by troytop** [comment]
For CAP 1.5 docs and release notes, do not preclude using Helm 3 (it works). Remove wording that  states Helm 2 is a requirement.

**Comment by btat** [comment]
Closed by https://github.com/SUSE/doc-cap/pull/741
