### ISSUE TITLE
[doc] Figure&nbsp;1.1:  Minimal Example Production Deployment 

### ISSUE THREAD

**Issue by risidoro** [SUSE/doc-cap#637]
Figure&nbsp;1.1:  Minimal Example Production Deployment 

https://documentation.suse.com/suse-cap/1.5.1/single-html/cap-guides/#fig-cap-min-prod-arch

Can you update the figure with the CAASP v4 ???

**Comment by btat** [comment]
This diagram was not included as part of the 2.0 release. If updates to the diagram are required for 1.x, please reopen.
