### ISSUE TITLE
[doc] 22.1  Deploy Minibroker - Name including randomized prefix

### ISSUE THREAD

**Issue by KucharczykL** [SUSE/doc-cap#642]
22.1  Deploy Minibroker

https://documentation.suse.com/suse-cap/1.5/single-html/cap-guides/#sec-cap-minibroker-deployment

After running `helm install suse/minibroker --namespace minibroker --name minibroker --set "defaultNamespace=minibroker"`, the created minibroker pod sometimes gets assigned a randomized prefix, e.g.: `nonexistent-anteater-minibroker-65ddd488c6-dvd9w`.

**Comment by btat** [comment]
Closing this as CAP-1128 has been created and is the more appropriate location.
