### ISSUE TITLE
[doc] 25.2  Enabling and Disabling the App-AutoScaler Service

### ISSUE THREAD

**Issue by it-slav** [SUSE/doc-cap#644]
25.2  Enabling and Disabling the App-AutoScaler Service

https://documentation.suse.com/suse-cap/1.5.1/html/cap-guides/cha-cap-app-autoscaler.html#sec-cap-enable-app-autoscaler

Is the version number necessary? It does not work with the version that is there, I used 2.19.1 and that worked today. Tomorrow there will be another version.

**Comment by btat** [comment]
The version number listed there is associated with the `suse/cf` Helm chart. Specifying the version number helps to prevent accidental upgrades to newer versions of the chart.

> It does not work with the version that is there, I used 2.19.1 and that worked today. Tomorrow there will be another version.

What version do you see there? Clicking the link you pasted shows `2.19.1` for me. The version will only change if you use the doc links for a different CAP release. If you continue to use the link from your example (CAP 1.5.1 docs) then the version will remain `2.19.1`. If you use the CAP 1.5 docs for example, then the version will be 2.18.0

**Comment by it-slav** [comment]
You are right, when looking in my history I tried to deploy with version2.9.1.
My bad.
Close the ticket with fat finger user ;-)
Thanks
PeterA

**Comment by btat** [comment]
👍
