### ISSUE TITLE
[doc] 25.4  Using the App-AutoScaler Service

### ISSUE THREAD

**Issue by it-slav** [SUSE/doc-cap#645]
25.4  Using the App-AutoScaler Service

https://documentation.suse.com/suse-cap/1.5.1/html/cap-guides/cha-cap-app-autoscaler.html#sec-cap-app-autoscaler-usage

The $AS_PASSWORD is empty

    peter@caasadmin:~/autoscaler> SECRET=$(kubectl get pods --namespace scf \
    --output jsonpath='{.items[?(.metadata.name=="api-group-0")].spec.containers[?(.name=="api-group")].env[?(.name=="INTERNAL_CA_CERT")].valueFrom.secretKeyRef.name}')
    peter@caasadmin:~/autoscaler> echo $SECRET
    secrets-2.19.1-1
    peter@caasadmin:~/autoscaler> AS_PASSWORD="$(kubectl get secret $SECRET --namespace scf --output jsonpath="{.data['autoscaler-service-broker-password']}" | base64 --decode)"
    peter@caasadmin:~/autoscaler> echo $AS_PASSWORD

    peter@caasadmin:~/autoscaler>

**Comment by KucharczykL** [comment]
As far as I can tell, the secret doesn't exist in at all. @btat any idea why that might be?

**Comment by btat** [comment]
@KucharczykL CAP-251 should contain the information needed to get AS running. The setup procedure is different after the AS version got bumped.

**Comment by it-slav** [comment]
I do not understand how https://github.com/SUSE/scf/pull/2446/files can help me get Autoscaler running.

**Comment by btat** [comment]
@it-slav that message was intended for KucharczykL (hence the @) on where he can find the information to work on this ticket with. In summary, there's no longer a broker for the AS so the `cf create-service-broker` command is not run, which in turn means the AS_PASSWORD is not needed (and does not exist).

**Comment by KucharczykL** [comment]
@it-slav The issue has been solved but please allow some time for the documentation.suse.com website to be updated.

**Comment by it-slav** [comment]
As a SUSE employee working with CAP, I would appreciate to get the updated doc before the official doc is updated. Is that possible?

**Comment by zoopster** [comment]
> As a SUSE employee working with CAP, I would appreciate to get the updated doc before the official doc is updated. Is that possible?

you can, anyone can, this is all public docs follow the updated diff in #647
