### ISSUE TITLE
Oldest supported version of Kubernetes on Azure

### ISSUE THREAD

**Issue by KucharczykL** [SUSE/doc-cap#656]
9.2  Create Resource Group and AKS Instance

https://documentation.suse.com/suse-cap/1.5/single-html/cap-guides/#sec-cap-create-aks-instance

This section mentions Kubernetes version 1.11.9 as the recommended (in the `az aks create` cluster command) but Azure seems to offer 1.13.11 as the lowest and 1.14.8 as the default recommended version.

**Comment by btat** [comment]
Make sure to coordinate with QA on this since we list the version that they test.

**Comment by KucharczykL** [comment]
Will remove the recommended Kubernetes version until a proper solution is created.

**Comment by KucharczykL** [comment]
Closing for now as there is no plan to add a recommended version in the near future.
