### ISSUE TITLE
Helm 2 links broken in the whole documentation

### ISSUE THREAD

**Issue by rabueker** [SUSE/doc-cap#662]
3.3  Usage of Helm Chart Fields in Cloud Application Platform

https://susedoc.github.io/doc-cap/develop/cap-guides/single-html/#id-1.3.4.3.5

Links to helm.sh lead  to "404 page not found"
i.E.
https://helm.sh/docs/developing_charts

Please update

**Comment by KucharczykL** [comment]
Helm developers changed the links on their website to point to the third version which has some major changes and all the old docs can now be found at v2.helm.sh. Will update.
