### ISSUE TITLE
7.1.3 - Example does not match description

### ISSUE THREAD

**Issue by zoopster** [SUSE/doc-cap#665]
7.1.3  Simple High Availability Configuration

https://documentation.suse.com/suse-cap/1.5/html/cap-guides/cha-cap-ha.html#sec-cap-ha-simple

The example for HA doesn't show how to set the HA option via the command line as stated in one of the paragraphs.

**Comment by zoopster** [comment]
Seems this may be a dup of #622

**Comment by btat** [comment]
The example and corresponding description were updated in 9aa2c1c to only mention using the config file, but looks like it was overwritten during subsequent merges resulting in an example that does not match the description. #672 fixes this.
