### ISSUE TITLE
[doc] 7.1.4  Example Custom High Availability Configurations

### ISSUE THREAD

**Issue by zoopster** [SUSE/doc-cap#666]
7.1.4  Example Custom High Availability Configurations

https://documentation.suse.com/suse-cap/1.5/html/cap-guides/cha-cap-ha.html#sec-cap-ha-custom

This shows the NGINX ingress controller cannot be used with an Embedded UAA, however I had thought this was resolved in 1.5.1 (noted in the release notes)?

**Comment by btat** [comment]
Thanks for catching this. https://github.com/SUSE/doc-cap/pull/673 removes the message. The change will be reflected in the 1.5.1 docs, once published, but will not be seen at the link provided since that is for the 1.5 docs.
