### ISSUE TITLE
Privileged must be enabled in kubelet only for Kube < 1.15

### ISSUE THREAD

**Issue by rabueker** [SUSE/doc-cap#669]
2.1  Kubernetes Requirements

https://susedoc.github.io/doc-cap/develop/cap-guides/single-html/#sec-cap-changes-kube-reqs

In Docu:
- Privileged must be enabled in kubelet

according to:
https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.15.md#node:

"The deprecated kubelet security controls AllowPrivileged, HostNetworkSources, HostPIDSources, and HostIPCSources have been removed. Enforcement of these restrictions should be done through admission control (such as PodSecurityPolicy) instead. (#77820, @dims)
The deprecated Kubelet flag --allow-privileged has been removed. Remove any use of the flag from your kubelet scripts or manifests. (#77820, @dims)"

CaasSP4 running with 1.5.2, so the requirement does not seem to apply anymore

**Comment by btat** [comment]
Thanks for catching this
