### ISSUE TITLE
[doc] 3.8  Releases and Associated Versions - suse/console 2.6.1 vs. 2.6.0?

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/doc-cap#679]
3.8  Releases and Associated Versions

https://documentation.suse.com/suse-cap/1.5.1/single-html/cap-guides/#id-1.3.4.3.10
----
In this table I see console 2.6.0 but helm search shows me 2.6.1 - so what is the one to use?

**Comment by btat** [comment]
2.6.1 should be used. The table on the page got outdated and has been fixed now. Thanks for catching this.
