### ISSUE TITLE
[doc] 5  Deploying SUSE Cloud Application Platform on SUSE CaaS Platform - SUSE SUSE

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/doc-cap#680]
5  Deploying SUSE Cloud Application Platform on SUSE CaaS Platform

https://documentation.suse.com/suse-cap/1.5.1/single-html/cap-guides/#cha-cap-depl-caasp
-----
Replace 
"back-end: one SUSE SUSE CaaS Platform " with
"back-end: one SUSE CaaS Platform "

**Comment by btat** [comment]
Thanks for catching this. Fixed in https://github.com/SUSE/doc-cap/pull/686
