### ISSUE TITLE
[doc] 5.1  Prerequisites - Dashboard node??

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/doc-cap#681]
5.1  Prerequisites

https://documentation.suse.com/suse-cap/1.5.1/single-html/cap-guides/#sec-cap-prereqs-prod
----
I assume this might be a "rest of CaaSP v3":

8 GB of memory per SUSE CaaS Platform dashboard and Kubernetes master nodes. 

-> AFAIK there is no "dashboard node" in CaaSP v4 anymore

This might need to be updated in the requirements

**Comment by btat** [comment]
Thanks for catching this. This change is included in the fix for #575 and will be reflected in the next update/publish.
