### ISSUE TITLE
Unclear AKS introduction

### ISSUE THREAD

**Issue by fsundermeyer** [SUSE/doc-cap#69]
@cornelius reported in [bsc 1094675](https://bugzilla.suse.com/show_bug.cgi?id=1094675):

There are two things which appear to be unclear to me in the introduction to the AKS section (http://docserv.suse.de/documents/CAP_1/cap-deployment/single-html/#cha.cap.depl-azure):

It talks about setting up an un-managed Kubernetes on AKS. AKS is a managed Kubernetes so I think it would be better to just say how to prepare AKS for installation of CAP, and maybe explain that AKS is a managed Kubernetes service.

The mention of the Kube minion is a bit confusing. On one hand I think the terminology used by Kubernetes is "node" now, not "minion" anymore. And on the other hand it's not clear what this actually means for somebody installing CAP. Is this a production setup or not? Would a load balancer make it one?

**Comment by cjschroder** [comment]
Thanks @cornelius, and thanks @fsundermeyer for converting bugzillas to nice GitHub issues.

 I resist "node" because in K8s-land that means only K8s hosts, while in the rest of the computing world a node is any device on a network. If it has an IP address it's a node.

**Comment by cjschroder** [comment]
https://github.com/SUSE/doc-cap/pull/76
