### ISSUE TITLE
[doc] 5.1  Prerequisites - CPU requirements for deployment on CaaSP v4?

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/doc-cap#690]
5.1  Prerequisites

https://documentation.suse.com/suse-cap/1.5.1/single-html/cap-guides/#sec-cap-prereqs-prod
-------------------------

How much CPU do we need in each worker node for CaaSP in case we want to run CAP on top?
-> could we get this added to the documentation?

**Comment by greygoo** [comment]
Judging from our test systems, I'd say the following values are the minimum to have it running with some basic workload. You will have to add more if your workload is higher of course:

1x Master: 2CPUs/8GB RAM/60GB Disk
2x Worker: 4CPUs/16GB RAM/100GB Disk
Persistent Storage: 40GB Disk fuer 1x CAP

**Comment by btat** [comment]
> Judging from our test systems, I'd say the following values are the minimum to have it running with some basic workload. You will have to add more if your workload is higher of course:
> 
> 1x Master: 2CPUs/8GB RAM/60GB Disk
> 2x Worker: 4CPUs/16GB RAM/100GB Disk
> Persistent Storage: 40GB Disk fuer 1x CAP

@greygoo are these numbers for HA?
