### ISSUE TITLE
External DB instructions

### ISSUE THREAD

**Issue by satadruroy** [SUSE/doc-cap#694]
We should add the following as a separate section:

https://github.com/SUSE/scf/wiki/CAP-1.5.2-Notes-(tag-2.20.x)#external-database

And, in that section, we should mention somewhere (already mentioned in the relnotes but worth repeating here):

Note if you are using external UAA with an external database you must set up two separate database instances; one for UAA and one for SCF. One external database instance for both an external UAA and an SCF setup is not supported and will cause data conflicts resulting in deployment failures.

The external database server *must* support both TLS and non-encrypted connections; if the external database server only accepts TLS connections some SCF components will not be able to communicate with the database server.

Note that Amazon RDS uses a CA that is not currently recognized as a well-known CA within UAA. Therefore, you must use the flag `env.UAADB_TLS` to `enabled_skip_all_validation` to disable server certificate validation for TLS connections to RDS. If you are using credhub, you will need to pass in the RDS CA via the `secrets.CREDHUB_DB_CA_CERT` flag to ensure credhub is able to validate the RDS server cert.

**Comment by btat** [comment]
Closed by #702
