### ISSUE TITLE
[doc] Figure&nbsp;1.1:  Minimal Example Production Deployment 

### ISSUE THREAD

**Issue by alexrenna** [SUSE/doc-cap#707]
Figure&nbsp;1.1:  Minimal Example Production Deployment 

https://documentation.suse.com/suse-cap/1.5.1/single-html/cap-guides/#fig-cap-min-prod-arch

the picture still shows Velum Dashboard, that is not present anymore on current CaaSP version 4

**Comment by btat** [comment]
Closing as duplicate of #637
