### ISSUE TITLE
Backup/Restore

### ISSUE THREAD

**Issue by fsundermeyer** [SUSE/doc-cap#71]
@cornelius reported in [bsc 1079617](https://bugzilla.suse.com/show_bug.cgi?id=1079617):

We need to document how to backup and restore a CF cluster so that it can be reinstalled without losing data.

Backup/Restore will be part of the 1.1 release. We will release it as an upstream plugin so it has a little bit different status than the rest of the product which we deliver through our own channels with the standard SUSE support.

Feature work on the backup and restore CLI plugin is tracked on Trello: https://trello.com/c/LW3nZuG9

**Comment by cjschroder** [comment]
https://trello.com/c/LW3nZuG9/454-backup-restore-cli-plugin
https://github.com/SUSE/cf-plugin-backup

**Comment by cjschroder** [comment]
https://github.com/SUSE/doc-cap/commit/b2401e44f9a7a62f11de3627aeb4f1f8deb36add
