### ISSUE TITLE
Clean up CaaSP content that resides outside of CaaSP chapter

### ISSUE THREAD

**Issue by btat** [SUSE/doc-cap#713]
In the early stages of the CAP documentation, all content was written with the assumption that CAP was deployed on CaaSP only. As support for other platforms became available, each platform was placed into their own chapter. With this change other sections should be generalized for any Kubernetes.

Review the entire docs for such instances.

Examples:
- Ch 1 About CAP
    - Minimum Requirements section
    - Platform Architecture

**Comment by KucharczykL** [comment]
In `cap_overview.xml`, we refer to minimum deployment on CaaSP. This is already described in their own documentation and probably also more up-to-date. Should we link directly to that instead of risking becoming outdated again when it changes?

**Comment by KucharczykL** [comment]
Reopening to track some more changes.
