### ISSUE TITLE
[doc] 13.1  Enabling Eirini

### ISSUE THREAD

**Issue by rssfed23** [SUSE/doc-cap#715]
13.1  Enabling Eirini

https://documentation.suse.com/suse-cap/1.5.2/html/cap-guides/cha-cap-depl-eirini.html#sec-cap-eirini-enable

The section says "As of SUSE Cloud Foundry 2.18.0, cf push with Eirini does not work on Amazon Elastic Kubernetes Service and Google Kubernetes Engine by default. To get cf push to work with Microsoft AKS and Google GKE, you need to apply a work"

Which one do you mean? - Amazon or Microsoft? - It switches either side of the sentence so is unclear to us which one you need to apply the workaround for. Please validate with the CAP team which one requires the workaround and update the docs. Thanks

**Comment by btat** [comment]
Thanks for catching this. Looks like a typo occurred when using a repeatable entity causing the wrong resulting output. The step itself is no longer required though, so its removal is used as the fix.
