### ISSUE TITLE
[doc] 3.7  DNS Management

### ISSUE THREAD

**Issue by troytop** [SUSE/doc-cap#717]
3.7  DNS Management

https://documentation.suse.com/suse-cap/1.5.2/single-html/cap-guides/#id-1.3.4.3.9

Link to DNS instructions for Public Cloud platforms rather than just referring to them, and add some generic DNS instructions for CaaSP section which doesn't appear to have any guidance (e.g. a BIND zone file example)

**Comment by HartS** [comment]
> uaa-uaa-public is in the uaa namespace, and the rest are in the scf namespace.

Maybe we should remove this, since users may be installing embedded UAA

**Comment by troytop** [comment]
We should document that there are (at least) two possible configurations.

**Comment by troytop** [comment]
> > uaa-uaa-public is in the uaa namespace, and the rest are in the scf namespace.
> 
> Maybe we should remove this, since users may be installing embedded UAA

We should document that there are (at least) two possible configurations.

**Comment by btat** [comment]
This section was removed during the 2.0 update. The relevant info on setting up DNS records were already located within the chapters for each deployment platform. This section was found in the "Admin Notes" chapter, which we tell users to read at the start of each deployment platform chapter. Placing the DNS mapping information in such a spot was not necessary as users are not required to create the records ahead of time.
