### ISSUE TITLE
LDAP integration

### ISSUE THREAD

**Issue by fsundermeyer** [SUSE/doc-cap#72]
@cornelius reported in [bsc 1079615](https://bugzilla.suse.com/show_bug.cgi?id=1079615):

We need to document how to integrate with an existing LDAP for user authentication.

One part is:

- Documentation for mapping the users from an external LDAP group (specially the initial IT ops ids) to CF roles (admin, orgManager) This is a common activity after setting un a customer environment and a bit convoluted step.

**Comment by cjschroder** [comment]
UAA doc page https://github.com/cloudfoundry/uaa/blob/master/docs/UAA-LDAP.md
