### ISSUE TITLE
[CAP-812] How do I get started on EKS?

### ISSUE THREAD

**Issue by btat** [SUSE/doc-cap#723]
See also: https://github.com/SUSE/kubecf/issues/17

**Comment by btat** [comment]
From https://github.com/SUSE/kubecf/issues/17#issuecomment-589165793

This article may be helpful https://starkandwayne.com/blog/running-cloud-foundry-on-kubernetes-using-kubecf/

**Comment by troytop** [comment]
When you get to this, check to see if the Blue Horizon installer GUI (in the marketplace) is supporting CAP 2.0. Docs should point to that and the cap-terraform scripts as options to a completely manual installation.

**Comment by btat** [comment]
Closed via #764, #812 ,#815 ,#817, #845, #846, #848, #851, #877

#883 opened for BH
