### ISSUE TITLE
[doc] 3.8  Releases and Associated Versions - Incorrect Stratos Metrics Version

### ISSUE THREAD

**Issue by gaktive** [SUSE/doc-cap#725]
3.8  Releases and Associated Versions

https://susedoc.github.io/doc-cap/master/single-html/cap-guides/#id-1.3.4.3.10

With CAP 1.5.2, Stratos Metrics is v1.1.2. This fixes its usage on Kubernetes 1.16.

**Comment by btat** [comment]
Gah, looks like the entity to track the version was updated...but we didn't actually use the entity in the table. Fixed now
