### ISSUE TITLE
[doc] 1.4.4  Detailed Services Diagram

### ISSUE THREAD

**Issue by gaktive** [SUSE/doc-cap#729]
1.4.4  Detailed Services Diagram

https://documentation.suse.com/suse-cap/1.5.2/single-html/cap-guides/#sec-cap-services-detailed

Figure 1.7 needs to be bigger in the PDF version. The noodly diagram on the layout requires some unnecessary zooming in when it could be flush with the margins.

**Comment by gaktive** [comment]
Question: how accurate is this figure with kubecf? @f0rmiga or @viovanov can assist from an architectural vantage.

**Comment by f0rmiga** [comment]
### About UAA:

The communication to `UAA` happens via the `Router`, and it doesn't have its own database instance, instead, it shares the same database with the rest of the instance groups.

### About the database:

It's about to be replaced by `PXC` (it's true for SCF already), therefore, MariaDB is inaccurate. Whether we will have a `proxy` in front of the database or not is still not clear.

### About NFS Persi Broker:

We don't have that yet.

---

@viovanov Did I miss something?
