### ISSUE TITLE
Table of Contents for 2.0 - Framework for Initial Docs

### ISSUE THREAD

**Issue by btat** [SUSE/doc-cap#735]
https://confluence.suse.com/display/CAP/CAP+2.0+-+Table+of+Contents+Planning

**Comment by btat** [comment]
@KucharczykL will update the confluence with the rearranged TOC

**Comment by KucharczykL** [comment]
Made some changes. Please take a look to make sure I haven't forgotten anything.

**Comment by btat** [comment]
> Made some changes. Please take a look to make sure I haven't forgotten anything.

Forgot to comment here, but changes look fine.

**Comment by btat** [comment]
Closing since all changes to placement/ordering of content is done
