### ISSUE TITLE
Document how to run CAP on non-CaaSP Kubernetes systems

### ISSUE THREAD

**Issue by fsundermeyer** [SUSE/doc-cap#74]
@cornelius reported in [bsc 1072943](https://bugzilla.suse.com/show_bug.cgi?id=1072943):

CAP runs not only on CaaSP but on any Kubernetes which is matching a few requirements on available features. We should at least document that this is possible.

**Comment by cjschroder** [comment]
https://github.com/SUSE/doc-cap/pull/80

**Comment by cjschroder** [comment]
based on  https://github.com/SUSE/scf/wiki/How-to-Install-SCF#requirements-for-kubernetes

**Comment by cjschroder** [comment]
closing with no technical review. Please open an issue to report any corrections.

**Comment by mook-as** [comment]
[cha.cap.depl-kube-requirements](http://docserv.nue.suse.com/documents/CAP_1/cap-deployment/html/cha.cap.depl-kube-requirements.html) seemed correct enough that there wasn't anything to object to, that's all :stuck_out_tongue:

**Comment by cjschroder** [comment]
@mook-as I know that perfection is often stunning. Still, it is nice to know that someone looked at it :)
