### ISSUE TITLE
[doc] 32.8  <code class="literal">mysql</code> Pods Fail to Start

### ISSUE THREAD

**Issue by andreas-mach** [SUSE/doc-cap#755]
32.8  <code class="literal">mysql</code> Pods Fail to Start

https://documentation.suse.com/suse-cap/1.5/single-html/cap-guides/index.html#sec-cap-tbl-mysql-failure

---

I was running into an issue to get the "mysql-0" pod up and running it was in the state:
"READY: 0/1 - STATUS: Running" in my case it was related to the configuration of the used NFS share.

I'd like to add a new section:

3. If the mysql pod is in state:READY: 0/1 - STATUS: Running

tux > kubectl get pods -n uaa
NAME                            READY     STATUS      RESTARTS   AGE
configgin-helper-0              1/1       Running     0          16m
mysql-0                         0/1       Running     0          16m
mysql-proxy-0                   1/1       Running     0          16m
post-deployment-setup-1-lg7vl   0/1       Completed   0          16m
secret-generation-1-fczw4       0/1       Completed   0          16m
uaa-0                           0/1       Running     0          16m

Please verify the mysql-0 pod and check if all files in "/var/vcap/store/" are owned by "vcap" user: 

tux > kubectl exec --stdin --tty --namespace uaa mysql-0 -- bash

mysql/0:/# cd /var/vcap/store/

mysql/0:/var/vcap/store# ls -al
total 12
drwxrwxrwx 4 vcap nobody 4096 Mar  9 07:41 .
drwxr-xr-x 1 root root     98 Mar  9 07:40 ..
drwx------ 2 vcap nobody 4096 Mar  9 07:41 mysql_audit_logs
drwx------ 6 vcap nobody 4096 Mar  9 07:42 pxc-mysql

---

You can test this, create a new file in your "mysql" container and verify the owner:

mysql/0:/var/vcap/store# su - vcap

mysql/0:~$ cd /var/vcap/store/

mysql/0:/var/vcap/store$ touch test

mysql/0:/var/vcap/store$ ls -al
total 12
drwxrwxrwx 4 vcap nobody 4096 Mar  9 08:11 .
drwxr-xr-x 1 root root     98 Mar  9 07:40 ..
drwx------ 2 vcap nobody 4096 Mar  9 07:41 mysql_audit_logs
drwx------ 6 vcap nobody 4096 Mar  9 07:42 pxc-mysql
-rw-rw-r-- 1 vcap nobody    0 Mar  9 08:11 test

---

Solution:
Please verify the configuration of your NFS share.

**Comment by btat** [comment]
Thanks for this! 

@KucharczykL can you add this to the 1.5 - 1.5.2 branches
