### ISSUE TITLE
[doc] 12  Eirini - link leads to incorrect target

### ISSUE THREAD

**Issue by otuominen** [SUSE/doc-cap#771]
12  Eirini

https://documentation.suse.com/suse-cap/1.5.2/single-html/cap-guides/#cha-cap-depl-eirini

Link http://eirini.cf is leading to http://www.freenom.link/

**Comment by btat** [comment]
I can't seem to find that link listed on https://www.cloudfoundry.org/project-eirini/ anymore, but it's still listed as the project site when going through https://www.cloudfoundry.org/projects/.

I've asked on Slack about the link and waiting to see if updates need to be made on our page.

**Comment by btat** [comment]
The Eirini folks on Slack said their domain expired. Since this will be fixed upstream I'll check the link periodically, but will close this issue for now.
