### ISSUE TITLE
add general guidance on DNS configuration for load balancers [edit]

### ISSUE THREAD

**Issue by cjschroder** [SUSE/doc-cap#78]
List CAP DNS requirements and brief overview of using Azure DNS

**Comment by troytop** [comment]
Changing the focus to a more general overview. Instructions for DNS will be slightly different between cloud provider load balancers and nginx-ingress

**Comment by gaktive** [comment]
Let's leave off the nginx ingress material for now until Eng sorts out the latest changes.

**Comment by cjschroder** [comment]
This is partially satisfied by https://github.com/SUSE/doc-cap/pull/344, https://github.com/SUSE/doc-cap/pull/340. This section 'DNS Management' https://susedoc.github.io/doc-cap/develop/cap-guides/html/cha.cap.depl.notes.html#id-1.3.4.3.6 needs to be expanded to cover CAP DNS requirements

**Comment by gaktive** [comment]
For guidance, let's document load balancers as the default and then move the existing non-LB material into something like a caveat.

**Comment by cjschroder** [comment]
WIP  https://github.com/SUSE/doc-cap/pull/373

**Comment by gaktive** [comment]
Reading through the deployment guide, we've mostly covered load balancers and DNS. Closing though let's pay attention to this as we start working on 2.0.
