### ISSUE TITLE
Clean up diagrams

### ISSUE THREAD

**Issue by cjschroder** [SUSE/doc-cap#79]
Diagrams are fuzzy. try Inkscape SVG

**Comment by gaktive** [comment]
Diagrams may need to re-evaluation with upcoming next version.

**Comment by btat** [comment]
Closing as:
- diagram contents were updated during the 2.0 release
- diagrams were converted from PNG to SVG in previous PRs.
- unused diagrams have been removed in https://github.com/SUSE/doc-cap/pull/895
