### ISSUE TITLE
[doc] 6.1  Deploy Stratos on SUSE® CaaS Platform - console is not 2.7.0 anymore - needs update

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/doc-cap#805]
6.1  Deploy Stratos on SUSE® CaaS Platform

https://documentation.suse.com/suse-cap/1.5.2/single-html/cap-guides/#sec-cap-stratos-prod

------

seems this is now 3.1.0 and we need details on the values.yaml

**Comment by btat** [comment]
Fixed via https://github.com/SUSE/doc-cap/commit/6e940e41f0101e479200dcf7b9531313303da35d
