### ISSUE TITLE
Addendum for CAP running on CaaSP 3

### ISSUE THREAD

**Issue by gaktive** [SUSE/doc-cap#82]
Context: https://kubernetes.io/docs/concepts/policy/pod-security-policy/
Internal bug: https://bugzilla.suse.com/show_bug.cgi?id=1097668

CaaSP 3 introduces PodSecurityPolicy (PSP) support (https://github.com/kubic-project/salt/pull/428). This change adds 2 PSP's:

    unprivileged (Default assigned to all users)
The unprivileged PodSecurityPolicy is intended to be a
reasonable compromise between the reality of Kubernetes workloads, and
suse:caasp:psp:privileged. By default, we'll grant this PSP to all
users and service accounts.

    privileged
The privileged PodSecurityPolicy is intended to be given
only to trusted workloads. It provides for as few restrictions as possible
and should only be assigned to highly trusted users.

Currently, all the pods are created using the default serviceAccount in their namespace so they have the unprivileged psp applied. For example, this means the nfs-broker can't create pods because privileged mode and privilege escalation are disabled by default (error: cannot set `allowPrivilegeEscalation` to *false* and `privileged` to *true*).

For CaaSP, we'll need to create our own pod policy that suits our needs.

QA CSS created a slightly different PSP as a workaround that is applied when creating the namespaces. It is based on the unprivileged PSP; the only difference is that it enables the privileged mode and the privilege escalation. This would go into a file called `cap-psp-rbac.yaml`:

```
---
apiVersion: extensions/v1beta1
kind: PodSecurityPolicy
metadata:
  name: suse.cap.psp
  annotations:
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: '*'
spec:
  # Privileged
  #privileged: false      	<<< default in suse.caasp.psp.unprivileged
  privileged: true
  # Volumes and File Systems
  volumes:
    # Kubernetes Pseudo Volume Types
    - configMap
    - secret
    - emptyDir
    - downwardAPI
    - projected
    - persistentVolumeClaim
    # Networked Storage
    - nfs
    - rbd
    - cephFS
    - glusterfs
    - fc
    - iscsi
    # Cloud Volumes
    - cinder
    - gcePersistentDisk
    - awsElasticBlockStore
    - azureDisk
    - azureFile
    - vsphereVolume
  allowedFlexVolumes: []
  allowedHostPaths:
    # Note: We don't allow hostPath volumes above, but set this to a path we
    # control anyway as a belt+braces protection. /dev/null may be a better
    # option, but the implications of pointing this towards a device are
    # unclear.
    - pathPrefix: /opt/kubernetes-hostpath-volumes
  readOnlyRootFilesystem: false
  # Users and groups
  runAsUser:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
  # Privilege Escalation
  #allowPrivilegeEscalation: false	   <<< default in suse.caasp.psp.unprivileged
  allowPrivilegeEscalation: true
  #defaultAllowPrivilegeEscalation: false  <<< default in suse.caasp.psp.unprivileged
  # Capabilities
  allowedCapabilities: []
  defaultAddCapabilities: []
  requiredDropCapabilities: []
  # Host namespaces
  hostPID: false
  hostIPC: false
  hostNetwork: false
  hostPorts:
  - min: 0
    max: 65535
  # SELinux
  seLinux:
    # SELinux is unsed in CaaSP
    rule: 'RunAsAny'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: suse:cap:psp
rules:
  - apiGroups: ['extensions']
    resources: ['podsecuritypolicies']
    verbs: ['use']
    resourceNames: ['suse.cap.psp']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cap:clusterrole
roleRef:
  kind: ClusterRole
  name: suse:cap:psp
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: default
  namespace: uaa
- kind: ServiceAccount
  name: default
  namespace: scf
- kind: ServiceAccount
  name: default
  namespace: stratos
```

As a note, it would be a good practice to explicitly set `allowPrivilegeEscalation` to *true* in the charts so the defaultAllowPrivilegeEscalation can be set to *false* in the PSP. This way, it gives a finer security control on what the pods are authorized to do and restrict the default authorizations.

For CaaSP 2 users, they can implement this workaround already since PSP is optional.

**Comment by cjschroder** [comment]
Beautifu, thanks @gaktive

**Comment by greygoo** [comment]
We tested with this on the engineering cloud and got Build 2.11.0 [1.2 RC1]  working finr on CaaSP3 with it. Internal docs at https://github.com/SUSE/cloudfoundry/wiki/Known-Good-Configurations#before-you-can-install-scf-on-caasp have been updated as well.

**Comment by cjschroder** [comment]
@gaktive @greygoo what namespace is this applied to? uaa, scf, and stratos?
e.g. `helm install suse/uaa --values cap-psp-rbac.yaml `

**Comment by cjschroder** [comment]
Never mind, I see the answer at https://github.com/SUSE/cloudfoundry/wiki/Known-Good-Configurations#before-you-can-install-scf-on-caasp

**Comment by cjschroder** [comment]
https://github.com/SUSE/doc-cap/pull/110

**Comment by cjschroder** [comment]
https://github.com/SUSE/doc-cap/commit/62d1a64c200029c924ffbd87f73d2ecb5e11c70d
