### ISSUE TITLE
Eirini single availability only

### ISSUE THREAD

**Issue by btat** [SUSE/doc-cap#823]
Need to add a note that Eirini will be SA/non-HA only

"Eirini will also be non-HA only based on problems with certain services like bits not working in HA at all"

**Comment by gaktive** [comment]
This may change based on testing since it was identified that HA could work; let me get the latest. The important thing we need to coach around this is that Eirini remains a tech preview.

**Comment by KucharczykL** [comment]
@gaktive Does this still apply or should we close the issue?

**Comment by gaktive** [comment]
Close it for now since RC2 showed better results.
