### ISSUE TITLE
cf-backup-plugin has no details into what it doesn't do.

### ISSUE THREAD

**Issue by gaktive** [SUSE/doc-cap#83]
This work may be already underway but the backup/restore plugin currently has a table regarding the scope of what it does do.

We should expand the scope in some way to incorporate what it doesn't do. For instance, we should tell operators prior to backing up that it won't do certain tasks, like handle custom buildpacks. The table we have in https://github.com/SUSE/cf-plugin-backup/blob/master/README.md doesn't feel like the right place for information like that; operators should be told earlier.

This type of list will need expansion but we can accommodate that for future updates. We need a structure of some sort first.

**Comment by cjschroder** [comment]
https://github.com/SUSE/doc-cap/pull/91
See how this works for you, @gaktive 
Preview at http://docserv.nue.suse.com/documents/CAP_1/cap-deployment/single-html/#cha.cap.backup-restore
