### ISSUE TITLE
[doc] 5.11  Add the Kubernetes Charts Repository

### ISSUE THREAD

**Issue by zoopster** [SUSE/doc-cap#857]
5.11  Add the Kubernetes Charts Repository:

https://susedoc.github.io/doc-cap/master/single-html/cap-guides/#sec-cap-addrepo-aks

helm search works differently in v2 vs v3.
helm search suse is proper for v2
helm search repo suse is proper for v3

**Comment by btat** [comment]
Thanks! Fixed in https://github.com/SUSE/doc-cap/pull/860
