### ISSUE TITLE
[doc] A.1  Complete suse/kubecf values.yaml File

### ISSUE THREAD

**Issue by zoopster** [SUSE/doc-cap#858]
A.1  Complete suse/kubecf values.yaml File:

https://susedoc.github.io/doc-cap/master/single-html/cap-guides/#app-kubecf-values-yaml

another one...helm 3 inspect is:
helm inspect chart suse/kubecf (it's mentioned that the output is suse/cf vs suse/kubecf

**Comment by btat** [comment]
Thanks! Fixed in https://github.com/SUSE/doc-cap/pull/860
