### ISSUE TITLE
[doc] 6.14.2  Example LDAP Integration - Missing ldapProfileFile and ldapGroupFile example files

### ISSUE THREAD

**Issue by gpoppino** [SUSE/doc-cap#887]
# 6.14.2  Example LDAP Integration:

https://documentation.suse.com/suse-cap/2.0/single-html/cap-guides/#id-1.3.4.6.17.4

## Missing files

Files for options `ldapProfileFile` and `ldapGroupFile` are mentioned but not included in the example configuration. These files are:

* ldap-search-and-bind.xml
* ldap-groups-map-to-scopes.xml

Without these files the integration with LDAP cannot be configured properly. 

The documentation should include an example of the contents of these files or a link to a repository where these can be found.

**Comment by btat** [comment]
Hi @gpoppino, in that section there are links to [1][UAA API Reference](http://docs.cloudfoundry.org/api/uaa/version/4.21.0/index.html#ldap) and [2][Cloud Foundry UAA-LDAP Documentation](https://github.com/cloudfoundry/uaa/blob/4.21.0/docs/UAA-LDAP.md), which provide more info on the `ldapProfileFile` and `ldapGroupFile` request fields.

The filenames are just predefined values accepted by the request field. The files are not provided by the user.

For example from [1], `ldapProfileFile`  is described as `The file to be used for group integration. Options are: ldap/ldap-groups-null.xml, ldap/ldap-groups-as-scopes.xml, ldap/ldap-groups-map-to-scopes.xml`. 

And from this [section](https://github.com/cloudfoundry/uaa/blob/4.21.0/docs/UAA-LDAP.md#group-mapping-configuration) of [2] you'll find the descriptions of what each value does.

```
Group Mapping Configuration

The property ldap.groups.file controls what group mapping is used, and is also a reference to a Spring XML configuration file. The different values are

    ldap/ldap-groups-null.xml - no groups will be retrieved
    ldap/ldap-groups-as-scopes.xml - group names will be derived from an attribute, like CN, in the group record
    ldap/ldap-groups-map-to-scopes.xml - groups will be mapped to UAA groups using the external_group_mapping table

The file exports a bean named ldapAuthoritiesPopulator to be used in the LDAP configuration files.
```

I tried finding the source for the files in [2], but could not find them. If you're curious about the contents of the file, you may want to check with upstream.
