### ISSUE TITLE
Scheduler vs logging [doc]  

### ISSUE THREAD

**Issue by phakkarainen** [SUSE/doc-cap#891]
Is this correct?

"scheduler
Part of the logging system that allows user applications to be bound to a syslog drain."

https://documentation.suse.com/suse-cap/2.0/single-html/cap-guides/#id-1.3.3.3.4.11.4

**Comment by KucharczykL** [comment]
* Current CAP docs: `Part of the logging system that allows user applications to be bound to a syslog drain.`
* CF website: `service exposed as a service broker in the PCF Marketplace. App developers use Scheduler to create, schedule and interact with jobs that execute on PCF.`
* https://network.pivotal.io/products/p-scheduler/info: `Create jobs to execute tasks (Diego tasks), Execute jobs on an ad hoc basis, Schedule jobs to execute on a recurring basis, View job status and history`

Unless I'm misunderstanding or these are two different things, seems like the definition in our docs does not conform to the upstream one.
