### ISSUE TITLE
[doc] 22.1  Using the cf CLI with SUSE Cloud Application Platform

### ISSUE THREAD

**Issue by phakkarainen** [SUSE/doc-cap#893]
22.1  Using the cf CLI with SUSE Cloud Application Platform:

helm status kubecf 
does not display the message for CAP 2.0.

https://documentation.suse.com/suse-cap/2.0/single-html/cap-guides/#sec-cap-cf-cli

**Comment by btat** [comment]
Looks like the NOTES.txt (https://github.com/cloudfoundry-incubator/kubecf/blob/master/deploy/helm/kubecf/templates/NOTES.txt) didn't make it into the current release for KubeCF (https://github.com/SUSE/kubernetes-charts-suse-com/tree/master/stable/kubecf/templates) whereas it did for the operator (https://github.com/SUSE/kubernetes-charts-suse-com/tree/master/stable/cf-operator/templates).

Given that's the case, I've just removed the snippets referencing the message for the time being (via PR https://github.com/SUSE/doc-cap/pull/934). They will be added back once the message is available again. The `helm` command will also need to be updated to include the namespace flag.
