### ISSUE TITLE
Localization prep

### ISSUE THREAD

**Issue by gaktive** [SUSE/doc-cap#901]
In anticipation of translating the CAP docs into 8 languages, we need to provide our docs team with .po files on the text that will be converted.

A tool like https://webtranslateit.com/en/docs/file_formats/docbook looks like it could help. We would target to translate this every minor release.

**Comment by KucharczykL** [comment]
Stefan mentioned this: https://github.com/openSUSE/release-notes-openSUSE/blob/Leap_15.2/Makefile
Haven't had time to look at it in detail yet.

**Comment by KucharczykL** [comment]
According to Frank, we can hand over the XML files directly.

**Comment by KucharczykL** [comment]
This has been sorted outside of Github.
