### ISSUE TITLE
[doc] 4.4  Storage Class

### ISSUE THREAD

**Issue by abonillabeeche** [SUSE/doc-cap#902]
4.4  Storage Class:

https://documentation.suse.com/suse-cap/2.0/single-html/cap-guides/#sec-cap-caasp-storage

1. The kubecf namespace does not yet exist.
2. sed's/"namespace":   needs a space between sed and 's

**Comment by KucharczykL** [comment]
We already address 1. in the troubleshooting section. I think mentioning that everywhere the user can encounter this would cause too much clutter.
I will fix 2.

Thank you for the report!
