### ISSUE TITLE
Update links to CaaSP docs to 4.2

### ISSUE THREAD

**Issue by KucharczykL** [SUSE/doc-cap#906]
For example: https://documentation.suse.com/suse-cap/1.5.2/single-html/cap-guides/#sec-cap-caasp-config

**Comment by KucharczykL** [comment]
In 2.0 this is fixed. Do we need to fix this in the maintenance branches as well?

**Comment by btat** [comment]
When 1.5.2 was released, we tested against CaaSP 4.1. I asked in the QA channel on Rocketchat whether CAP 1.5.2 and CaaSP 4.2 is a tested/supported case. Once we get an answer, we can update if needed.

**Comment by btat** [comment]
Response from CAP QA is that CAP 1.5.2 on CaaSP 4.2 is an untested scenario. It was suggested to check with CaaSP QA to see which CAP they tested with 4.2

**Comment by KucharczykL** [comment]
Martin Kravec confirmed that they tested CaaSP 4.2 with 1.5.2.

**Comment by btat** [comment]
Closed via #922
