### ISSUE TITLE
Add .editorconfig to maintain file format consistency

### ISSUE THREAD

**Issue by KucharczykL** [SUSE/doc-cap#909]
See https://editorconfig.org/

It would be a small change that enables the supported editors to automatically set things like line endings and indent style without any effort from the author. Thoughts?

For CAP the example .editorconfig would look like this (according to https://documentation.suse.com/style/current/single-html/docu_styleguide/#sec-format-xml):

```
root = true                                                                         
                                                                                    
[*.xml]                                                                             
end_of_line = lf                                                                    
insert_final_newline = false                                                        
charset = utf-8                                                                     
indent_style = space                                                                
indent_size = 1
```

**Comment by btat** [comment]
After a quick read through (and no actual testing), this looks fine to me, but have a few questions/concerns. 

- In the event we adopt usage of editorconfig and a new contributor comes along and uses an editor that doesn't have native support and hasn't downloaded the necessary plugin, will anything break when they push? Will formatting be lost?

- I skimmed through the style guide and couldn't find an answer, but I think we should confirm whether their are guidelines for adding third-party files/tools like this to the repo. Perhaps we could consult with the the docs team style committee. 

- Although not automatic like editorconfig, we already have `daps xmlformat` as part of our current toolchain (we just need to remember to use it every now and then).

**Comment by KucharczykL** [comment]
* Nothing breaks. This only allows editors to automatically adjust their settings on the fly in the specified way as opposed to the author having to monitor that for different projects themself.

* I brought it up in the documentation team channel and this is so far considered to be part of a larger push towards having some unity and/or preset editor config for our docs. It is supposed to be discussed in the future. Apart from that, I don't think there are any guidelines. Personally I consider the change to be so small that the decision doesn't IMO necessitate whole team consensus buy YMMV.

* While ultimately a similar result is achieved with both, .editorconfig kind of prevents you from having to use that in the first place because the editor will make sure it follows the style. I've personally never used `daps xmlformat` and I'm unsure whether it's actively being used by others.

**Comment by btat** [comment]
Alright, let's give this a try.
