### ISSUE TITLE
Architecture diagram

### ISSUE THREAD

**Issue by cornelius** [SUSE/doc-cap#94]
We need a diagram explaining the architecture of CAP. We have some material but it needs to be adapted to what is suitable for customers needs.

**Comment by cornelius** [comment]
I have some diagrams in my talk from OSDC: https://osdc.de/osdc-2018/videos-slides-2018/ (search for Cloud Foundry on this page). We also have some internal material. I'll send you a link.

@viovanov is probably the person who could help you best there.

**Comment by btat** [comment]
Resolved by PR https://github.com/SUSE/doc-cap/pull/180
