### ISSUE TITLE
Ingress Controller w/ CaaSP

### ISSUE THREAD

**Issue by btat** [SUSE/doc-cap#954]
The current section needs to be updated to be applicable to on-prem/CaaSP setups. With managed Kubernetes (pub clouds) the IaaS provider will provision a LB with external IP, but usually this will not be the case with CaaSP where the operator may need to set up some kind of LB themselves.

@KucharczykL please consult w/ Sebi since we has experience with CaaSP+LB experience.

**Comment by KucharczykL** [comment]
I'm reading notes written by @svollath. Need to do some tests.

**Comment by KucharczykL** [comment]
See https://github.com/SUSE/doc-caasp/issues/970#issuecomment-696757329

Does this mean the issue is no longer relevant?

**Comment by KucharczykL** [comment]
As per the comment above, CaaSP indicated that this will not be supported.
