### ISSUE TITLE
Out-of-date example describing how to create named database with Minibroker

### ISSUE THREAD

**Issue by bdekany** [SUSE/doc-cap#957]
18.1.3  Using Minibroker with Applications:

https://documentation.suse.com/suse-cap/2.0/single-html/cap-guides/#sec-cap-minibroker-application-usage

Hi, in the important note regarding creating a mariaDB service, the JSON part is not working.
The option is not mariaDatabase - which looks like an heritage from mysql.

Wrong command: cf create-service mariadb 10-1-34 my-db  -c **'{"mariadbDatabase":"mydb"}'**
Good command: cf create-service mariadb 10-1-34 my-db  -c **'{"db":{"name":"mydb"}}'**

Regards

**Comment by f0rmiga** [comment]
Thanks for reporting this @bdekany. What we need to do is to point the user to the correct Helm chart upstream instead of giving copy-paste commands.
The upstream charts can change its interface and the same problem would occur again.
@btat Thoughts?

**Comment by KucharczykL** [comment]
Would the upstream be this: https://github.com/helm/charts/blob/master/stable/mariadb/values.yaml#L125

**Comment by btat** [comment]
From #doc-cap 

```
... we need to document what the platform operator needs to do, and then remove the very specific notes about how to provision mysql and postgresql
the CAP docs need to explain how the override works, and why you would use it

Yes! We need to have good instructions how to dig the upstream charts to discover parameters. 
```
