### ISSUE TITLE
How to set up a registry for an air-gapped environment

### ISSUE THREAD

**Issue by cornelius** [SUSE/doc-cap#96]
When the CAP system is completely separated from the Internet (i.e. there is an air-gap), there needs to be a way how to get the container images from the SUSE registry to the system where they are supposed to be installed. This can be solved by using a registry, pushing images there, and then moving the registry to the separated environment.

We need to document how to do that.

**Comment by cornelius** [comment]
More context: https://bugzilla.suse.com/show_bug.cgi?id=1072942

**Comment by cornelius** [comment]
Draft documentation: [How to setup an air-gapped mirror of the SUSE registry.pdf](https://github.com/SUSE/doc-cap/files/2145729/How.to.setup.an.air-gapped.mirror.of.the.SUSE.registry.pdf)

**Comment by troytop** [comment]
Check with Jason Evans who has created training material for offline installation.

**Comment by gaktive** [comment]
Based on current prospect activity, we need to get this rolling again.

**Comment by tgeek77** [comment]
I'm going to write up a short guide on how I did this this week. My entire lab environment is 99% air-gapped. I never did find a way to make minibroker work offline, but it's been a few months so maybe that has changed.

**Comment by tgeek77** [comment]
Network Requirements:
Dedicated internal IP ranges or DHCP (KVM's NAT DHCP is not enough)
Local DNS server with wildcard records

Steps
1. Add Cap Helm Repo
2. Download Helm Charts
3. Extract image names from Charts (may require grep-gu and sed-fu or lots of manual searching)
4. Update the image mirror script (see https://gitlab.suse.de/jsevans/CAP101/blob/master/scripts/smt_machine/mirror-container-images.sh)
5. Set up a local image Repo
6. Run the image mirror script (this will take a long time even on a fast connection)
7. Update any non-CAP Helm charts to point to the local image repo
8. Make sure scf-config-values.yaml is pointing to the local image repo
9. Make sure Kubernetes accepts the certificates for your local image repo. Previously done in Velum (don't know how to do it in CaaSP4/Kubic yet)
10. Install UAA, SCF, and Stratos
11. Minibroker has it's own version of tiller but it is also hardcoded to pull mysql, postgres, etc. images from upstream and will ignore the local image repo. This is the 1% online requirement so far.

**Comment by jandubois** [comment]
We have updated all the CAP charts to include an `imagelist.txt` file that lists all images from the `registry.suse.com` registry under the `cap` organization. They can be mirrored to a local registry with the following script:

```
#!/bin/bash

MIRROR=registry.home

set -ex

function mirror {
    CHART=$1
    CHARTDIR=$(mktemp -d)
    helm fetch suse/$1 --untar --untardir=${CHARTDIR}
    IMAGES=$(cat ${CHARTDIR}/**/imagelist.txt)
    for IMAGE in ${IMAGES}; do
        echo $IMAGE
        docker pull registry.suse.com/cap/$IMAGE
        docker tag registry.suse.com/cap/$IMAGE $MIRROR/cap/$IMAGE
        docker push $MIRROR/cap/$IMAGE
    done
    docker save -o ${CHART}-images.tar.gz \
           $(perl -E "say qq(registry.suse.com/cap/\$_) for @ARGV" ${IMAGES})
    rm -r ${CHARTDIR}
}

mirror cf
mirror uaa
mirror console
mirror metrics
mirror cf-usb-sidecar-mysql
mirror cf-usb-sidecar-postgres
```

The script above will *both* mirror to a local registry *and* save the images in a local tarball that can be restored with `docker load foo-images.tgz`. In general only one of these mechanisms will be needed.

The `minibroker` chart will be supported as soon as we make the next release (currently in QA) because the current chart doesn't use a tagged image, but `minibroker:latest`.

The `nginx-ingress` chart is not supported by this mechanism because it is not part of the `cap` organization (and cannot be configured with the `kube.registry.hostname` setting at deploy time either).

It is however simple enough to manually parse the helm chart for the image names and do a manual `docker pull && docker tag && docker push` on them.

**Comment by flavio** [comment]
When using CaaSP the mirroring can be done in a different way. There's also a patch applied to our docker engine and to CRI-O that doesn't force the user to rename all the container images to reference the internal mirror.

You can find more information here:

  * [Deployment instructs for mirror](https://www.suse.com/documentation/suse-caasp-3/book_caasp_deployment/data/sec_deploy_scenarios_airgap.html)
  * [Howto make CaaSP aware of the mirror](https://www.suse.com/documentation/suse-caasp-3/book_caasp_admin/data/sec_admin_velum_mirror.html)

The later point will change with CaaSP v4. We will update the documentation accordingly.

CC: @chentex who worked on helm-mirror and has familiarity with the whole workflow
