### ISSUE TITLE
Diego cells and storage require special configuration

### ISSUE THREAD

**Issue by gaktive** [SUSE/doc-cap#961]
https://github.com/cloudfoundry-incubator/kubecf/pull/1264 and https://github.com/cloudfoundry-incubator/kubecf/issues/1287 point to the fact that we need to highlight that Diego cells should exist without other CF services for storage purposes.

The mechanism has changed and PVC vs. other storage behaviour needs to documented. There may be differences in implementation depending on the Kubernetes deployment, specifically if there's a public cloud involved.

**Comment by andreas-kupries** [comment]
Note:
  * https://jira.suse.com/browse/CAP-1567
  * cloudfoundry-incubator/kubecf-docs/pull/23
  * cloudfoundry-incubator/kubecf/issues/1287
