### ISSUE TITLE
[doc] 4.11  Add the Kubernetes Charts Repository

### ISSUE THREAD

**Issue by bsix16868** [SUSE/doc-cap#965]
4.11  Add the Kubernetes Charts Repository:

https://documentation.suse.com/suse-cap/2.0/html/cap-guides/cha-cap-depl-caasp.html#sec-cap-addrepo-caasp

List chart names should be helm search _suse_ and not helm search repo _suse_

**Comment by zoopster** [comment]
Can you verify which helm version you are using?
CAP2 requires helm 3 and the proper helm 3 search command is `helm search repo suse` to list all of the charts in the repo named suse

**Comment by bsix16868** [comment]
We are on helm 2.  

Brian Six
San Diego, CA
858-699-8701
DX AG6RJ

**Comment by btat** [comment]
Hi @bsix16868, as @zoopster (thanks John!) indicated CAP 2 requires Helm 3. This is listed earlier in the chapter in the `Install the Helm Client` section. I will go ahead and close this issue. If you came across any areas which mention Helm 2, please let us know and we will correct it.
