### ISSUE TITLE
[doc] 4.3  Install the Helm Client

### ISSUE THREAD

**Issue by zoopster** [SUSE/doc-cap#968]
4.3  Install the Helm Client:

https://documentation.suse.com/en-us/suse-cap/2.0/html/cap-guides/cha-cap-depl-caasp.html#id-1.3.4.4.6

Seems we may wish to point out helm3 is only in the 4.5 repository (we have a 4 and a 4.5 repository now).

**Comment by btat** [comment]
Fixed indirectly via https://github.com/SUSE/doc-cap/commit/77c8b4281c728d4d708c9738e79d600d5c0b7448 (for 2.0) and https://github.com/SUSE/doc-cap/commit/4f7439499ac24d03d17c11300ba1c56c1707db23 (for 2.0.1), which links to the CaaSP 4.5 docs which in turn directs users to use the 4.5 module.
