### ISSUE TITLE
[doc] 17.2.4  Performing a Raw Data Backup / Restore

### ISSUE THREAD

**Issue by mudler** [SUSE/doc-cap#984]
17.2.4  Performing a Raw Data Restore:

https://documentation.suse.com/suse-cap/2.0/html/cap-guides/cha-cap-backup-restore.html#sec-cap-raw-data-restore-procedure

also the Backup section are taken from SCF, but the commands and the values file are mostly different for KubeCF and not valid for CAP 2.x. Will document here my findings. There  are some notes available here https://github.com/cloudfoundry-incubator/kubecf/blob/master/doc/encryption_key_rotation.md#importing-encryption-keys

**Comment by btat** [comment]
This should be fixed by https://github.com/SUSE/doc-cap/pull/976 which was based off the the steps in the description of CAP-1532.
